=== ibmresilient/resilient-community-apps/fn_trusteer_ppd/payload_samples/trusteer_ppd_update_alert_classification/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "data": {
          "type": "object",
          "properties": {
            "api_request_id": {
              "type": "string"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "trusteer_ppd_session_id": {
          "type": "string"
        },
        "trusteer_ppd_feedback": {
          "type": "string"
        },
        "trusteer_ppd_application_id": {
          "type": "string"
        },
        "trusteer_ppd_fraud_mo": {}
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_trusteer_ppd/payload_samples/trusteer_ppd_update_alert_classification/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "success",
    "message": "OK",
    "data": {
      "api_request_id": "82825B58-70CA-4B04-9BD2-E65E112AA417"
    }
  },
  "raw": null,
  "inputs": {
    "trusteer_ppd_session_id": "eaa3aef168e8aeadfb606bf2637c21f",
    "trusteer_ppd_feedback": "pending_confirmation",
    "trusteer_ppd_application_id": "demo_app",
    "trusteer_ppd_fraud_mo": null
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-trusteer-ppd",
    "package_version": "1.0.0",
    "host": "laptop.local",
    "execution_time_ms": 3517,
    "timestamp": "2023-02-28 16:57:36"
  }
}

=== ibmresilient/resilient-community-apps/fn_trusteer_ppd/payload_samples/trusteer_ppd_update_classification_in_alert_datatable/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "num_rows_updated": 5
  },
  "raw": null,
  "inputs": {
    "trusteer_ppd_session_id": "xxx3aef168e8aeadfb606bf2637cxxx",
    "incident_id": 3326,
    "trusteer_ppd_classification": "Confirmed fraud (Stolen device)"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-trusteer-ppd",
    "package_version": "1.0.0",
    "host": "laptop.local",
    "execution_time_ms": 5647,
    "timestamp": "2023-03-01 10:23:36"
  }
}
