=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_find_a_system/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "EPOComputerProperties.ParentID": {
            "type": "integer"
          },
          "EPOComputerProperties.ComputerName": {
            "type": "string"
          },
          "EPOComputerProperties.Description": {},
          "EPOComputerProperties.ComputerDescription": {},
          "EPOComputerProperties.TimeZone": {
            "type": "string"
          },
          "EPOComputerProperties.DefaultLangID": {
            "type": "string"
          },
          "EPOComputerProperties.UserName": {
            "type": "string"
          },
          "EPOComputerProperties.DomainName": {
            "type": "string"
          },
          "EPOComputerProperties.IPHostName": {
            "type": "string"
          },
          "EPOComputerProperties.IPV6": {},
          "EPOComputerProperties.IPAddress": {
            "type": "string"
          },
          "EPOComputerProperties.IPSubnet": {},
          "EPOComputerProperties.IPSubnetMask": {},
          "EPOComputerProperties.IPV4x": {},
          "EPOComputerProperties.IPXAddress": {
            "type": "string"
          },
          "EPOComputerProperties.SubnetAddress": {
            "type": "string"
          },
          "EPOComputerProperties.SubnetMask": {
            "type": "string"
          },
          "EPOComputerProperties.NetAddress": {
            "type": "string"
          },
          "EPOComputerProperties.OSType": {
            "type": "string"
          },
          "EPOComputerProperties.OSVersion": {
            "type": "string"
          },
          "EPOComputerProperties.OSCsdVersion": {
            "type": "string"
          },
          "EPOComputerProperties.OSBuildNum": {
            "type": "integer"
          },
          "EPOComputerProperties.OSPlatform": {
            "type": "string"
          },
          "EPOComputerProperties.OSOEMID": {
            "type": "string"
          },
          "EPOComputerProperties.CPUType": {
            "type": "string"
          },
          "EPOComputerProperties.CPUSpeed": {
            "type": "integer"
          },
          "EPOComputerProperties.NumOfCPU": {
            "type": "integer"
          },
          "EPOComputerProperties.CPUSerialNumber": {
            "type": "string"
          },
          "EPOComputerProperties.TotalPhysicalMemory": {
            "type": "integer"
          },
          "EPOComputerProperties.FreeMemory": {
            "type": "integer"
          },
          "EPOComputerProperties.FreeDiskSpace": {
            "type": "integer"
          },
          "EPOComputerProperties.TotalDiskSpace": {
            "type": "integer"
          },
          "EPOComputerProperties.IsPortable": {
            "type": "integer"
          },
          "EPOComputerProperties.Vdi": {
            "type": "integer"
          },
          "EPOComputerProperties.OSBitMode": {
            "type": "integer"
          },
          "EPOComputerProperties.LastAgentHandler": {},
          "EPOComputerProperties.UserProperty1": {},
          "EPOComputerProperties.UserProperty2": {},
          "EPOComputerProperties.UserProperty3": {},
          "EPOComputerProperties.UserProperty4": {},
          "EPOComputerProperties.UserProperty5": {},
          "EPOComputerProperties.UserProperty6": {},
          "EPOComputerProperties.UserProperty7": {},
          "EPOComputerProperties.UserProperty8": {},
          "EPOComputerProperties.Free_Space_of_Drive_C": {
            "type": "integer"
          },
          "EPOComputerProperties.Total_Space_of_Drive_C": {
            "type": "integer"
          },
          "EPOLeafNode.Tags": {
            "type": "string"
          },
          "EPOLeafNode.ExcludedTags": {
            "type": "string"
          },
          "EPOLeafNode.LastUpdate": {},
          "EPOLeafNode.ManagedState": {
            "type": "integer"
          },
          "EPOLeafNode.AgentGUID": {},
          "EPOLeafNode.AgentVersion": {},
          "EPOBranchNode.AutoID": {
            "type": "integer"
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "mcafee_epo_systems": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_get_all_users/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": [
    {
      "id": 1,
      "name": "admin",
      "fullName": "",
      "email": "",
      "phoneNumber": "",
      "disabled": false,
      "admin": true,
      "authType": "pwd",
      "authDetails": "",
      "notes": "",
      "allowedIPs": ""
    },
    {
      "id": 6,
      "name": "New user",
      "fullName": "",
      "email": "",
      "phoneNumber": "",
      "disabled": false,
      "admin": false,
      "authType": "pwd",
      "authDetails": "",
      "notes": "",
      "allowedIPs": ""
    },
    {
      "id": 5,
      "name": "richard-test",
      "fullName": "Richard Test",
      "email": "richard@test.com",
      "phoneNumber": "7394034758",
      "disabled": false,
      "admin": false,
      "authType": "pwd",
      "authDetails": "",
      "notes": "Hello",
      "allowedIPs": ""
    },
    {
      "id": 2,
      "name": "system",
      "fullName": "",
      "email": "",
      "phoneNumber": "",
      "disabled": true,
      "admin": true,
      "authType": "pwd",
      "authDetails": "",
      "notes": "",
      "allowedIPs": ""
    }
  ],
  "raw": null,
  "inputs": {
    "incident_id": 4057,
    "datatable_name": "mcafee_epo_users"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-mcafee-epo",
    "package_version": "3.0.0",
    "host": "local",
    "execution_time_ms": 820,
    "timestamp": "2023-10-09 10:55:20"
  }
}
