=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_assign_policy_to_group/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "boolean"
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "mcafee_epo_product_id": {
          "type": "string"
        },
        "mcafee_epo_group_id": {
          "type": "integer"
        },
        "mcafee_epo_object_id": {
          "type": "integer"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_add_system/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": true,
  "raw": null,
  "inputs": {
    "mcafee_epo_push_agent_install_path": null,
    "mcafee_epo_push_agent_package_path": null,
    "mcafee_epo_push_agent_force_install": false,
    "mcafee_epo_group_id": 2,
    "mcafee_epo_push_agent": false,
    "mcafee_epo_push_agent_domain_name": null,
    "mcafee_epo_flatten_tree_structure": false,
    "mcafee_epo_allow_duplicates": false,
    "mcafee_epo_delete_if_removed": false,
    "mcafee_epo_push_agent_username": null,
    "mcafee_epo_uninstall": false,
    "mcafee_epo_push_agent_skip_if_installed": false,
    "mcafee_epo_system_name_or_id": "richard test1",
    "mcafee_epo_push_agent_suppress_ui": false,
    "mcafee_epo_push_agent_password": null
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-mcafee-epo",
    "package_version": "3.0.0",
    "host": "local",
    "execution_time_ms": 787,
    "timestamp": "2023-10-09 10:26:00"
  }
}

=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_add_permission_sets_to_user/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": true,
  "raw": null,
  "inputs": {
    "mcafee_epo_username": "new user",
    "mcafee_epo_permsetname": "Global Reviewer"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-mcafee-epo",
    "package_version": "3.0.0",
    "host": "local",
    "execution_time_ms": 625,
    "timestamp": "2023-10-09 13:17:32"
  }
}

=== ibmresilient/resilient-community-apps/fn_mcafee_epo/payload_samples/mcafee_epo_assign_policy_to_group/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": true,
  "raw": null,
  "inputs": {
    "mcafee_epo_product_id": "EPOAGENTMETA",
    "mcafee_epo_group_id": 3,
    "mcafee_epo_object_id": 4
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-mcafee-epo",
    "package_version": "3.0.0",
    "host": "local",
    "execution_time_ms": 702,
    "timestamp": "2023-10-09 13:20:24"
  }
}
