=== ibmresilient/resilient-community-apps/fn_webex/payload_samples/webex_delete_room/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "status_code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "webex_room_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_webex/payload_samples/webex_create_meeting/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "id": "7abca37c1c124cb2a4e74661f4a8c47e",
    "meetingNumber": "25967357926",
    "title": "Soar Sample Instant Meeting",
    "agenda": "Testing the application",
    "password": "abcd12345",
    "phoneAndVideoSystemPassword": "22231234",
    "meetingType": "meetingSeries",
    "state": "active",
    "timezone": "UTC",
    "start": "2022-08-11T13:33:00Z",
    "end": "2022-08-11T14:18:00Z",
    "hostUserId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS85ODM0YjBlYi1mZmY1LTRjY2YtYTcwOC04Nzk1YmFjYjQ3NzU",
    "hostDisplayName": "admin@examples-5xth.wbx.ai",
    "hostEmail": "admin@examples-5xth.wbx.ai",
    "hostKey": "109420",
    "siteUrl": "examples-5xth.webex.com",
    "webLink": "https://examples-5xth.webex.com/examples-5xth/j.php?MTID=m4a809400de110cbedaa89ff5e55b3d73",
    "sipAddress": "25967357926@examples-5xth.webex.com",
    "dialInIpAddress": "173.243.2.68",
    "enabledAutoRecordMeeting": "false",
    "allowAnyUserToBeCoHost": "false",
    "allowFirstUserToBeCoHost": "false",
    "allowAuthenticatedDevices": "true",
    "enabledJoinBeforeHost": "false",
    "joinBeforeHostMinutes": "0",
    "enableConnectAudioBeforeHost": "false",
    "excludePassword": "false",
    "publicMeeting": "false",
    "enableAutomaticLock": "false",
    "unlockedMeetingJoinSecurity": "allowJoin",
    "telephony": "accessCode:25967357926",
    "callInNumbers": "label:United States Toll",
    "callInNumber": "+1-000-000-0000",
    "tollType": "toll",
    "links": "rel:globalCallinNumbers",
    "href": "/v1/meetings/7abca37c1c124cb2a4e74661f4a8c47e/globalCallinNumbers",
    "method": "GET",
    "meetingOptions": "enabledChat:true",
    "enabledVideo": "true",
    "enabledPolling": "false",
    "enabledNote": "true",
    "noteType": "allowAll",
    "enabledClosedCaptions": "false",
    "enabledFileTransfer": "true",
    "enabledUCFRichMedia": "true",
    "sessionTypeId": "3",
    "scheduledType": "meeting",
    "simultaneousInterpretation": "enabled:false",
    "enabledBreakoutSessions": "false",
    "status": true
  },
  "raw": null,
  "inputs": {
    "webex_meeting_name": "Soar Sample Instant Meeting",
    "webex_meeting_password": "abcd12345",
    "webex_meeting_agenda": "Testing the application"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-webex",
    "package_version": "2.0.0",
    "host": "AppHost",
    "execution_time_ms": 5448,
    "timestamp": "2022-08-11 13:31:40"
  }
}

=== ibmresilient/resilient-community-apps/fn_webex/payload_samples/fn_create_meeting/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "id": "ae6049cbb70840a2899eeef49a6931db",
    "meetingNumber": "25962157846",
    "title": "Webex Initial Test",
    "password": "abcd1234",
    "phoneAndVideoSystemPassword": "22231234",
    "meetingType": "meetingSeries",
    "state": "active",
    "timezone": "UTC",
    "start": "2022-07-16T14:06:00Z",
    "end": "2022-07-16T14:40:00Z",
    "hostUserId": "Y2lzY29zcGFyazovL3VzL1BFT1BMRS9hNDE4YjJiMC02MTg2LTRlMjAtYmY0Yi0zNDFkMzJmZGU4NTk",
    "hostDisplayName": "admin@calvinwynne-8xjq.wbx.ai",
    "hostEmail": "admin@calvinwynne-8xjq.wbx.ai",
    "hostKey": "492825",
    "siteUrl": "calvinwynne-8xjq.webex.com",
    "webLink": "https://calvinwynne-8xjq.webex.com/calvinwynne-8xjq/j.php?MTID=mf668e6d5f22862e3d6d790b0b4fc5465",
    "sipAddress": "25962157846@calvinwynne-8xjq.webex.com",
    "dialInIpAddress": "173.243.2.68",
    "enabledAutoRecordMeeting": "false",
    "allowAnyUserToBeCoHost": "false",
    "allowFirstUserToBeCoHost": "false",
    "allowAuthenticatedDevices": "true",
    "enabledJoinBeforeHost": "false",
    "joinBeforeHostMinutes": "0",
    "enableConnectAudioBeforeHost": "false",
    "excludePassword": "false",
    "publicMeeting": "false",
    "enableAutomaticLock": "false",
    "unlockedMeetingJoinSecurity": "allowJoin",
    "telephony": "accessCode:25962157846",
    "callInNumbers": "label:United States Toll",
    "callInNumber": "+1-650-479-3208",
    "tollType": "toll",
    "links": "rel:globalCallinNumbers",
    "href": "/v1/meetings/ae6049cbb70840a2899eeef49a6931db/globalCallinNumbers",
    "method": "GET",
    "meetingOptions": "enabledChat:true",
    "enabledVideo": "true",
    "enabledPolling": "false",
    "enabledNote": "true",
    "noteType": "allowAll",
    "enabledClosedCaptions": "false",
    "enabledFileTransfer": "true",
    "enabledUCFRichMedia": "true",
    "sessionTypeId": "3",
    "scheduledType": "meeting",
    "simultaneousInterpretation": "enabled:false",
    "enabledBreakoutSessions": "false",
    "status": true
  },
  "raw": null,
  "inputs": {
    "webex_meeting_name": "Webex Initial Test",
    "webex_meeting_password": "abcd1234",
    "webex_meeting_start_time": 1657976762000,
    "webex_meeting_agenda": "",
    "webex_meeting_end_time": 1657978856000
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-webex",
    "package_version": "1.0.0",
    "host": "Calvins-MacBook-Pro.local",
    "execution_time_ms": 2276,
    "timestamp": "2022-07-15 14:14:05"
  }
}

=== ibmresilient/resilient-community-apps/fn_webex/payload_samples/webex_delete_teamsrooms/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status_code": 204,
    "message": "Successfully deleted Room : Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vNDlmOWI5MjAtMzA0Ni0xMWVkLTk1Y2MtNTMzZDM5ZTQ5YmQ1"
  },
  "raw": null,
  "inputs": {
    "webex_entity_id": "Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vNDlmOWI5MjAtMzA0Ni0xMWVkLTk1Y2MtNTMzZDM5ZTQ5YmQ1",
    "webex_roomteam_selector": "Room"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-webex",
    "package_version": "2.0.0",
    "host": "AppHost",
    "execution_time_ms": 5104,
    "timestamp": "2022-02-12 14:01:16"
  }
}
