=== ibmresilient/resilient-community-apps/fn_ocm/payload_samples/on_call_manager_get_incident/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "state": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        },
        "team": {
          "type": "string"
        },
        "closedOwner": {
          "type": "string"
        },
        "closedTeam": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "displayId": {
          "type": "string"
        },
        "createdTime": {
          "type": "string"
        },
        "lastChanged": {
          "type": "string"
        },
        "firstInProgressTime": {
          "type": "string"
        },
        "resolvedTime": {
          "type": "string"
        },
        "eventSummary": {
          "type": "object",
          "properties": {
            "events": {
              "type": "integer"
            },
            "severities": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "severity": {
                    "type": "integer"
                  },
                  "count": {
                    "type": "integer"
                  }
                }
              }
            },
            "severities10": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "severity": {
                    "type": "integer"
                  },
                  "count": {
                    "type": "integer"
                  }
                }
              }
            },
            "maxSeverities10Seen": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "severity": {
                    "type": "integer"
                  },
                  "count": {
                    "type": "integer"
                  }
                }
              }
            },
            "openSeverities10": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "severity": {
                    "type": "integer"
                  },
                  "count": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "priority": {
          "type": "integer"
        },
        "escalated": {
          "type": "boolean"
        },
        "wasEscalated": {
          "type": "boolean"
        },
        "correlationDetails": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            }
          }
        },
        "accessScopes": {
          "type": "array"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "ocm_incident_id": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_ocm/payload_samples/on_call_manager_create_comment/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {},
  "raw": null,
  "inputs": {
    "ocm_incident_comment": "hello",
    "ocm_comment_author": "me",
    "ocm_incident_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-ocm",
    "package_version": "1.0.0",
    "host": "my.app.host",
    "execution_time_ms": 6816,
    "timestamp": "2025-05-23 11:13:18"
  }
}
