=== ibmresilient/resilient-community-apps/fn_netdevice/payload_samples/fn_netdevice_config/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "docker": {
          "type": "object",
          "properties": {
            "config_command": {
              "type": "string"
            },
            "config_result": {
              "type": "string"
            },
            "status": {
              "type": "string"
            }
          }
        }
      }
    },
    "raw": {
      "type": "string"
    },
    "inputs": {
      "type": "object",
      "properties": {
        "netdevice_ids": {
          "type": "string"
        },
        "netdevice_config_cmd": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_netdevice/payload_samples/fn_netdevice_query/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "docker": {
      "send_command": "ls",
      "send_result": "\nintermediate.cer  snap",
      "status": "success"
    }
  },
  "raw": "",
  "inputs": {
    "netdevice_ids": "docker",
    "netdevice_use_textfsm": false,
    "netdevice_send_cmd": "ls"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-netdevice",
    "package_version": "1.1.1",
    "host": "my.app.host",
    "execution_time_ms": 14006,
    "timestamp": "2025-04-01 15:18:47"
  }
}
