=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_add_attachments_to_soar_case/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "rapid7_insight_idr_attachments": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "rapid7_insight_idr_incident_id": {
          "type": "integer"
        },
        "rapid7_insight_idr_rrn": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_get_investigation/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "rapid7_insight_idr_investigation": {
      "rrn": "rrn:investigation:us2:eeeeeeee-ccc4-4ccc-8eee-eeeeeeeeeeee:investigation:AAAAAAAAAA",
      "organization_id": "e4463fba-cd64-427c-8fc9-f9e1983f24e1",
      "title": "1st investigation",
      "source": "USER",
      "status": "INVESTIGATING",
      "priority": "LOW",
      "last_accessed": "2023-12-01T22:41:02.993Z",
      "created_time": "2023-11-10T15:55:12.182Z",
      "disposition": "MALICIOUS",
      "assignee": null,
      "first_alert_time": null,
      "latest_alert_time": null,
      "responsibility": null,
      "entity_url": "https://us2.api.insight.rapid7.com/op/6E85858585854#/investigations/rrn:investigation:us2:eeeeeeee-cccc-4c4c-8fc9-f9e1983f24e1:investigation:AAAAAAAAAA"
    }
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_rrn": "rrn:investigation:us12:cccccccc-cd64-427c-8fc9-f9e1983f24e1:investigation:3AAAAAAAAAA"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "Book-Pro.local",
    "execution_time_ms": 229,
    "timestamp": "2023-12-04 10:24:18"
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_list_attachments/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "data": [
      {
        "rrn": "rrn:collaboration:us2:e4463fba-cd64-427c-8fc9-f9e1983f24e1:attachment:9JF5ST900Y1H",
        "creator": {
          "type": "USER",
          "name": "AdminUser"
        },
        "created_time": "2023-12-12T15:36:10.258Z",
        "file_name": "test.txt",
        "mime_type": "text/plain",
        "size": 40,
        "scan_status": "CLEAN"
      }
    ]
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_incident_id": 2228,
    "rapid7_insight_idr_rrn": "rrn:investigation:us2:e4463fba-cd64-427c-8fc9-f9e1983f24e1:investigation:JSPDKLRG7UWY"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "mylaptop",
    "execution_time_ms": 6807,
    "timestamp": "2023-12-12 11:34:29"
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_get_alert_evidence/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "data": {
      "evidences": [
        {
          "rrn": "rrn:alerts:us2:e4463fba-cd64-427c-8fc9-f9e1983f24e1:evidence:1:fcd21bbeec66b34322c57b50478014ef",
          "version": 1,
          "created_at": "2024-01-14T11:07:37.329397Z",
          "updated_at": "2024-01-14T11:07:37.329397Z",
          "evented_at": "2024-01-14T11:07:36.998Z",
          "external_source": "IDR ABA",
          "event_type": "raw",
          "data": "{\"timestamp\":\"2024-01-10T13:51:12.000Z\",\"hostname\":\"r7-test1\",\"appname\":\"sshd\",\"source_data\":\"Jan 10 08:51:12 r7-test1 sshd[19076]: error: maximum authentication attempts exceeded for root from 9.61.113.106 port 54336 ssh2 [preauth]\",\"custom_data\":{\"invalid-login\":\"maximum authentication attempts exceeded for\"}}"
        }
      ],
      "metadata": {
        "index": 0,
        "size": 1,
        "items_in_index": 1,
        "total_items": 1,
        "is_last_index": true
      }
    }
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_alert_rrn": "rrn:alerts:us2:e4463fba-cd64-427c-8fc9-f9e1983f24e1:alert:1:17c2b65f73ba0d975e9d24d446a9e91c",
    "rapid7_insight_idr_rrn": "rrn:investigation:us2:e4463fba-cd64-427c-8fc9-f9e1983f24e1:investigation:8V1AAAAAAA5F"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "mylaptop",
    "execution_time_ms": 9332,
    "timestamp": "2024-02-12 13:57:09"
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_set_status/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "rrn": "rrn:investigation:us2:eeeeeeeee-c4c4-427c-8fc9-f9efe1e1e1e1e1:investigation:3XAAXAAXAAXAA",
    "organization_id": "e4463fba-cd64-427c-8fc9-f9e1e1e1e1e1e1e1",
    "title": "Our 1st investigation",
    "source": "USER",
    "status": "CLOSED",
    "priority": "LOW",
    "last_accessed": "2023-12-08T17:30:12.959Z",
    "created_time": "2023-11-10T15:55:12.182Z",
    "disposition": "BENIGN",
    "assignee": null,
    "first_alert_time": null,
    "latest_alert_time": null,
    "responsibility": null
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_threat_command_free_text": "<div class=\"rte\"><div>Admin User closing as BENIGN from SOAR December 8, 2023</div></div>",
    "rapid7_insight_idr_status": "CLOSED",
    "rapid7_insight_idr_disposition": "BENIGN",
    "rapid7_insight_idr_threat_command_close_reason": "ProblemSolved",
    "rapid7_insight_idr_incident_id": 2211,
    "rapid7_insight_idr_rrn": "rrn:investigation:us2:eeeeeeeee-c4c4-427c-8fc9-f9efe1e1e1e1e1:investigation:3XAAXAAXAAXAA"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "laptop.local",
    "execution_time_ms": 93166,
    "timestamp": "2023-12-08 12:30:12"
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_get_comments/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "count": 1
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_incident_id": 2195,
    "rapid7_insight_idr_rrn": "rrn:investigation:us2:eeeeeeee-cccc-4c4c-8fc9-f9e19e19e1:investigation:AAAAAAAAAA"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "mylaptop",
    "execution_time_ms": 59301,
    "timestamp": "2023-12-06 11:56:52"
  }
}

=== ibmresilient/resilient-community-apps/fn_rapid7_insight_idr/payload_samples/rapid7_insight_idr_set_priority/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "rrn": "rrn:investigation:us2:eeeee222-cccc-dddc-8fc9-f9e19e19e1:investigation:2B9B9B9B9B9",
    "organization_id": "e4463fba-cd64-427c-8fc9-f9e1983f24e1",
    "title": "investigation 4",
    "source": "USER",
    "status": "INVESTIGATING",
    "priority": "LOW",
    "last_accessed": "2023-12-11T15:31:41.564Z",
    "created_time": "2023-11-28T20:09:36.546Z",
    "disposition": "UNDECIDED",
    "assignee": {
      "name": "Admin User",
      "email": "admin@example.com"
    },
    "first_alert_time": null,
    "latest_alert_time": null,
    "responsibility": null
  },
  "raw": null,
  "inputs": {
    "rapid7_insight_idr_priority": "LOW",
    "rapid7_insight_idr_incident_id": 2220,
    "rapid7_insight_idr_rrn": "rrn:investigation:us2:eeeee222-cccc-dddc-8fc9-f9e19e19e1:investigation:2B9B9B9B9B9"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-rapid7-insight-idr",
    "package_version": "1.0.0",
    "host": "mylaptop.local",
    "execution_time_ms": 21848,
    "timestamp": "2023-12-11 10:31:47"
  }
}
