=== ibmresilient/resilient-community-apps/fn_urlhaus/payload_samples/fn_urlhaus_submission/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "string"
    },
    "raw": {
      "type": "string"
    },
    "inputs": {
      "type": "object",
      "properties": {
        "urlhaus_artifact_value": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_urlhaus/payload_samples/fn_urlhaus_submission/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": "inserted: https://www.autohausmeister.eu\n",
  "raw": "",
  "inputs": {
    "urlhaus_artifact_value": "https://www.autohausmeister.eu"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-urlhaus",
    "package_version": "1.0.3",
    "host": "97472623-103e-44d1-a1da-c1d6296cbf8e-669f5f5bfc-sg65t",
    "execution_time_ms": 330,
    "timestamp": "2024-09-20 15:53:23"
  }
}

=== ibmresilient/resilient-community-apps/fn_sep/payload_samples/fn_sep_update_fingerprint_list/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": "",
  "raw": "\"\"",
  "inputs": {
    "sep_domainid": "6E70F043092E5BB93F74FD57C083F99E",
    "sep_hash_value": "0b9e4cb2af3dd1686accf0c469ce7b60",
    "sep_fingerprintlist_name": "Blacklist",
    "sep_fingerprintlist_content": "[{'SHA256': '9a4e26d0c4ab855d5346bae28272bbeeb1ab713b29a4aab030770655f05acc25'}, {'MD5': 'FF8C053969C0A52FF267D25138C71553', 'SHA256': '02E188239C4A7761C2F4C63964B6A754E15A388980F4050AC8C327D1FA30255F'}, {'MD5': 'FF8D7335A370D17A1379A949AF595F78', 'SHA256': '6E46434DACCDED82FA235FA14A019C20CF3AAFDAAB3F8EB81EBD0195C8F1D909'}, {'MD5': 'FF8D847F4173DBFCAF0A25C6C17C7B99', 'SHA256': 'BC56124B126D2A2F468125C38789FF19C9655FDD3A84990A1B90E2F91BCA1FD9'}, {'MD5': 'FF8F37FECFB4F7A56531E413883E03F5', 'SHA256': 'AD49D17F25670CF54B14DC7FE3EC086D9FCB92DEB4375B598AB95ECCD676CDBC'}, {'MD5': 'FF8FFEA7310D9A4A642CC8018227B91B', 'SHA256': '924D3456B5D72F6792CAE92895CFA9C0FEBA74616D92C8CD63639F77646B6B05'}, {'MD5': 'FF9171426D5A9490D548B08A5CA9C805', 'SHA256': '1F83EF7D0548828F101A6C760F1D208E2B220186ED71E38942D6CF6EF95FF756'}, {'MD5': 'FF91FA115BA27CD56716623DC6933946', 'SHA256': '05C2FB7565D2953D46E458D96000CD589AC14C4E4C33E718E38BE4739A9F7504'}, {'MD5': 'FF92B0EA7579E691C1FF669FAB5AC186', 'SHA256': '048E17562A6C601D3EAFF05FF62318944C9E7083825F587AD0F5C1C2C26CBD71'}, {'MD5': 'FF93C7959F24921381B8338686B0509C', 'SHA256': '2C6DCF143C41A5780DD24B48CA08EFC96595D86F4DB1FCD10D59E28EC1DBB0E2'}, {'MD5': 'FF95B2B128EB6B0BDDDF39CD05C78A0F', 'SHA256': 'DF1AE05C349A5C4E9D3187D0D85BD6172FB131BD5B826A1FFC947DB9A09F3DCF'}, {'MD5': 'FF9932C30F72B19E57D9B07F230487E7', 'SHA256': 'FBD7F130718C6A73E0AFD15D1F8D843426604A866EC63624357F8A952B484AD1'}, {'MD5': 'FF995A3411623293F7E3FD72143D04AB', 'SHA256': 'ACEA65301D759F922BDB1AB8DD52B57828FF4D64106A93C3EEAF89553466EA58'}, {'MD5': 'FF9CD8F4947AD1474D29187220BC3972', 'SHA256': 'AE17F31CBEEC0471392A42E85CB8B258351351212AB028C0B6B5C101C76083D9'}, {'MD5': 'FF9CF495023DD6D5BCE4187214B1469B', 'SHA256': '8D9FE0851D4D35D312F35E83618F63DFCBB4A045B5348468E04AE3CA61782F74'}, {'MD5': 'FF9D51FB459CF535F33003FABB0E7FD9', 'SHA256': '6D36FEB1167103BFE37251D1B049C449466A21590710F1E7F20C9B0C69511F7B'}, {'MD5': 'FF9E058DAC27FCC739884D3DBE43D81F', 'SHA256': '8C6A42FC8D9262A7E84C39566AB25931FBD77A7F9B5F1806DB69B297ADC87F3C'}, {'MD5': 'FF9E1E7E499D8C6336FA697C7142FA0C', 'SHA256': 'FD8862560FFA44B8177F1B1E053C1E820F2E19636F28E75A9AC427DBA0E15534'}, {'MD5': 'FF9E62ECB2BFD5B9CA608A40A96DEB04', 'SHA256': '95A9CB94CCB3F30029E1C977B63A845FE129C02E6CAF26AD234AB66AA9AF1C6C'}, {'MD5': 'FFA44FD7FEDA32632E8CE84AD0F9101B', 'SHA256': '2A0746A7876C1A430F9C9A5BE4BE28CAA2FF4F73477651AE5CC74462278F333B'}, {'MD5': 'FFA6335553397F28CA47ADC34343CA62', 'SHA256': '0D43D4D40C9854EB158DDE164699D02F47B21D68CEACAFEB2F469587B861C356'}]",
    "sep_description": "Fingerprint list 'Blacklist'",
    "sep_fingerprintlist_id": "C5C4CAC9092E5BB9315A5137B5B8DC8B"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-sep",
    "package_version": "1.2.0",
    "host": "local",
    "execution_time_ms": 1685,
    "timestamp": "2024-07-11 10:29:26"
  }
}
