=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_get_module_activity/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {},
        "properties": {
          "type": "object",
          "properties": {
            "definition": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "type": {},
            "parameterSets": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "parameters": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "isMandatory": {
                          "type": "boolean"
                        },
                        "isDynamic": {
                          "type": "boolean"
                        },
                        "position": {
                          "type": "integer"
                        },
                        "valueFromPipeline": {
                          "type": "boolean"
                        },
                        "valueFromPipelineByPropertyName": {
                          "type": "boolean"
                        },
                        "valueFromRemainingArguments": {
                          "type": "boolean"
                        },
                        "description": {},
                        "validationSet": {
                          "type": "array"
                        }
                      }
                    }
                  }
                }
              }
            },
            "outputTypes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              }
            },
            "creationTime": {
              "type": "string"
            },
            "lastModifiedTime": {
              "type": "string"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "activity_name": {
          "type": "string"
        },
        "account_name": {
          "type": "string"
        },
        "resource_group_name": {
          "type": "string"
        },
        "module_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_extrahop/payload_samples/funct_extrahop_rx_add_detection_note/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "result": "success"
  },
  "raw": null,
  "inputs": {
    "extrahop_update_time": 0,
    "extrahop_note": "\nIBM SOAR 10/04/2023 15:36:28\n[SOAR Case - 3080](https://host0.ibm.com:443/#incidents/3080)\nIBM SOAR 10/04/2023 14:00:50\n[SOAR Case - 3390](https://host1.ibm.com:443/#incidents/3390)\nIBM SOAR 2023-04-10 14:18:35\n[SOAR case - '3390'](Closed with resolution summary: 'Not an issue')",
    "extrahop_detection_id": 4294967305
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-extrahop",
    "package_version": "1.0.0",
    "host": "MBP",
    "execution_time_ms": 4470,
    "timestamp": "2023-04-10 14:18:48"
  }
}

=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_list_schedule_by_automation_account/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "value": [
      {
        "id": "/subscriptions/abcdefgh-1234-abcd-1234-a1b2c3d4e5f6/resourceGroups/demoassets/providers/Microsoft.Automation/automationAccounts/automation1/schedules/s",
        "name": "s",
        "type": "Microsoft.Automation/AutomationAccounts/Schedules",
        "properties": {
          "description": "",
          "startTime": "2023-08-29T12:05:00-04:00",
          "startTimeOffsetMinutes": -240.0,
          "expiryTime": "2023-08-29T12:05:00-04:00",
          "expiryTimeOffsetMinutes": -240.0,
          "isEnabled": true,
          "nextRun": "2023-08-29T12:05:00-04:00",
          "nextRunOffsetMinutes": -240.0,
          "interval": null,
          "frequency": "OneTime",
          "creationTime": "2023-08-23T16:05:14.3633333+00:00",
          "lastModifiedTime": "2023-08-23T17:09:35.4666667+00:00",
          "timeZone": "America/New_York",
          "advancedSchedule": null
        }
      },
      {
        "id": "/subscriptions/abcdefgh-1234-abcd-1234-a1b2c3d4e5f6/resourceGroups/demoassets/providers/Microsoft.Automation/automationAccounts/automation1/schedules/tester",
        "name": "tester",
        "type": "Microsoft.Automation/AutomationAccounts/Schedules",
        "properties": {
          "description": "",
          "startTime": "2023-08-08T14:35:00-04:00",
          "startTimeOffsetMinutes": -240.0,
          "expiryTime": "2023-08-08T14:35:00-04:00",
          "expiryTimeOffsetMinutes": -240.0,
          "isEnabled": true,
          "nextRun": null,
          "nextRunOffsetMinutes": 0.0,
          "interval": null,
          "frequency": "OneTime",
          "creationTime": "2023-08-08T18:05:08.1333333+00:00",
          "lastModifiedTime": "2023-08-08T18:05:08.1333333+00:00",
          "timeZone": "America/New_York",
          "advancedSchedule": null
        }
      },
      {
        "id": "/subscriptions/abcdefgh-1234-abcd-1234-a1b2c3d4e5f6/resourceGroups/demoassets/providers/Microsoft.Automation/automationAccounts/automation1/schedules/tester1324",
        "name": "tester1324",
        "type": "Microsoft.Automation/AutomationAccounts/Schedules",
        "properties": {
          "description": "something",
          "startTime": "2023-08-25T08:40:00+00:00",
          "startTimeOffsetMinutes": 0.0,
          "expiryTime": "2023-08-25T08:40:00+00:00",
          "expiryTimeOffsetMinutes": 0.0,
          "isEnabled": true,
          "nextRun": "2023-08-25T08:40:00+00:00",
          "nextRunOffsetMinutes": 0.0,
          "interval": null,
          "frequency": "OneTime",
          "creationTime": "2023-08-24T15:31:44.2666667+00:00",
          "lastModifiedTime": "2023-08-24T15:31:44.2666667+00:00",
          "timeZone": "Etc/UTC",
          "advancedSchedule": null
        }
      }
    ]
  },
  "raw": null,
  "inputs": {
    "account_name": "automation1",
    "resource_group_name": "demoassets"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-azure-automation-utilities",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 1400,
    "timestamp": "2023-08-24 11:37:57"
  }
}

=== ibmresilient/resilient-community-apps/fn_relations/payload_samples/relations_auto_close_child_incidents/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "incidents": [
      2097
    ]
  },
  "raw": null,
  "inputs": {
    "relations_parent_incident_id": 2096
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "3.1.0",
    "host": "localhost",
    "execution_time_ms": 2514,
    "timestamp": "2024-01-17 11:32:49"
  }
}

=== ibmresilient/resilient-community-apps/fn_salesforce/payload_samples/salesforce_get_contact/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "salesforce_contact": {
      "attributes": {
        "type": "Contact",
        "url": "/services/data/v58.0/sobjects/Contact/003Hr00002REwc8IAD"
      },
      "Id": "003Hr00002REwc8IAD",
      "IsDeleted": false,
      "MasterRecordId": null,
      "AccountId": null,
      "LastName": "Doe",
      "FirstName": "John",
      "Salutation": "Mr.",
      "Name": "John Doe",
      "OtherStreet": null,
      "OtherCity": null,
      "OtherState": null,
      "OtherPostalCode": null,
      "OtherCountry": null,
      "OtherLatitude": null,
      "OtherLongitude": null,
      "OtherGeocodeAccuracy": null,
      "OtherAddress": null,
      "MailingStreet": null,
      "MailingCity": null,
      "MailingState": null,
      "MailingPostalCode": null,
      "MailingCountry": null,
      "MailingLatitude": null,
      "MailingLongitude": null,
      "MailingGeocodeAccuracy": null,
      "MailingAddress": null,
      "Phone": null,
      "Fax": null,
      "MobilePhone": null,
      "HomePhone": null,
      "OtherPhone": null,
      "AssistantPhone": null,
      "ReportsToId": null,
      "Email": null,
      "Title": null,
      "Department": null,
      "AssistantName": null,
      "LeadSource": null,
      "Birthdate": null,
      "Description": null,
      "OwnerId": "005Hr00000COneZIAT",
      "CreatedDate": "2023-06-16T18:29:41.000+0000",
      "CreatedById": "005Hr00000COneZIAT",
      "LastModifiedDate": "2023-06-16T18:29:41.000+0000",
      "LastModifiedById": "005Hr00000COneZIAT",
      "SystemModstamp": "2023-06-16T18:29:41.000+0000",
      "LastActivityDate": null,
      "LastCURequestDate": null,
      "LastCUUpdateDate": null,
      "LastViewedDate": "2023-07-17T18:58:39.000+0000",
      "LastReferencedDate": "2023-07-17T18:58:39.000+0000",
      "EmailBouncedReason": null,
      "EmailBouncedDate": null,
      "IsEmailBounced": false,
      "PhotoUrl": null,
      "Jigsaw": null,
      "JigsawContactId": null,
      "IndividualId": null,
      "Level__c": null,
      "Languages__c": null
    }
  },
  "raw": null,
  "inputs": {
    "salesforce_contact_id": "003Hr00002REwc8IAD"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-salesforce",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 308,
    "timestamp": "2023-07-17 15:04:52"
  }
}

=== ibmresilient/resilient-community-apps/fn_microsoft_defender/payload_samples/defender_update_incident/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "@odata.context": "https://api.securitycenter.microsoft.com/api/$metadata#Incidents/$entity",
    "incidentId": 67,
    "incidentUri": "https://security.microsoft.com/incidents/67?tid=82319d65-80f7-431f-8ee7-57bae5b231c2",
    "redirectIncidentId": null,
    "incidentName": "[SAMPLE ALERT] MicroBurst exploitation toolkit used to extract keys to your storage accounts (Preview)",
    "createdTime": "2025-05-16T17:18:40.14Z",
    "lastUpdateTime": "2025-06-26T16:17:12.7739069Z",
    "assignedTo": null,
    "classification": "Unknown",
    "determination": "NotAvailable",
    "status": "Resolved",
    "severity": "High",
    "tags": [],
    "comments": [
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://wumb.org/ succeeded with attachment: override",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:02.2373446Z"
      },
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://wumb.org/ succeeded with attachment: https://wumb.org/",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:02.2361541Z"
      },
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://www.darkreading.com/ succeeded with attachment: https://www.darkreading.com/",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:02.4351735Z"
      },
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://www.darkreading.com/ succeeded with attachment: dark reading",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:02.6161014Z"
      },
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://www.darkreading.com/ succeeded with attachment: dark reading2",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:02.7755103Z"
      },
      {
        "comment": "Created by IBM SOAR<br>Snapshot URL for https://www.darkreading.com/ succeeded with attachment: https://www.darkreading.com/",
        "createdBy": "API-App:defender",
        "createdTime": "2025-06-26T14:55:03.1939816Z"
      },
      {
        "comment": "Created by IBM SOAR<br>done",
        "createdBy": "defender",
        "createdTime": "2025-06-26T16:17:12.7738668Z"
      }
    ],
    "alerts": [
      {
        "alertId": "dc37baef9d-89b0-955e-e745-655e52288919",
        "providerAlertId": "37baef9d-89b0-955e-e745-655e52288919",
        "incidentId": 67,
        "serviceSource": "MicrosoftDefenderForCloud",
        "creationTime": "2025-05-16T17:18:40.1Z",
        "lastUpdatedTime": "2025-05-16T17:18:41.7833333Z",
        "resolvedTime": null,
        "firstActivity": "2025-05-16T17:17:28.143969Z",
        "lastActivity": "2025-05-16T17:17:28.143969Z",
        "title": "[SAMPLE ALERT] MicroBurst exploitation toolkit used to extract keys to your storage accounts (Preview)",
        "description": "THIS IS A SAMPLE ALERT: MicroBurst's exploitation toolkit was used to extract keys to your storage accounts. This was detected by analyzing Azure Activity logs and resource management operations in your subscription.",
        "category": "Collection",
        "status": "New",
        "severity": "High",
        "investigationId": null,
        "investigationState": "UnsupportedAlertType",
        "classification": null,
        "determination": null,
        "detectionSource": "DefenderForResourceManager",
        "detectorId": "SIMULATED_ARM_MicroBurst.AZStorageKeysREST",
        "***": null,
        "actorName": null,
        "threatFamilyName": null,
        "mitreTechniques": [],
        "devices": [],
        "entities": []
      }
    ]
  },
  "raw": null,
  "inputs": {
    "defender_classification": "Unknown",
    "defender_incident_id": 67,
    "defender_determination": "NotAvailable",
    "defender_comment": "<div class=\"soar-rte-content\"><p>done</p></div>",
    "defender_tags": "",
    "defender_incident_status": "Resolved"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-microsoft-defender",
    "package_version": "1.3.0",
    "host": "my.app.host",
    "execution_time_ms": 241155,
    "timestamp": "2025-06-26 12:17:12"
  }
}

=== ibmresilient/resilient-community-apps/fn_axonius/payload_samples/axonius_get_device_by_query/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "assets": [
      {
        "internal_axon_id": "ca1df3031a00e387c8a7da086272f2b6",
        "adapters": [
          "cisco_meraki_adapter",
          "counter_act_adapter",
          "crowd_strike_adapter",
          "deep_security_adapter",
          "epo_adapter",
          "google_mdm_adapter",
          "paloalto_panorama_adapter",
          "sccm_adapter",
          "service_now_adapter",
          "tanium_adapter",
          "tanium_asset_adapter",
          "zoom_adapter"
        ],
        "adapter_list_length": 12,
        "labels": [
          "Shirley"
        ],
        "specific_data.data.hostname_preferred": "DESKTOP-shirleyc",
        "specific_data.data.last_used_users_departments_association": [
          "Legal",
          "Product"
        ],
        "specific_data.data.name": [
          "DESKTOP-shirleyc",
          "DESKTOP-shirleyc",
          "DESKTOP-shirleyc",
          "DESKTOP-shirleyc",
          "DESKTOP-shirleyc",
          "DESKTOP-shirleyc"
        ],
        "specific_data.data.os.type_distribution": [
          "Windows XP",
          "Windows XP",
          "Windows XP",
          "Windows XP",
          "Windows XP",
          "Windows XP",
          "Windows XP"
        ],
        "specific_data.data.last_used_users": [
          "shirley.cook@demo.local",
          "van.greer@demo.local",
          "shirley.cook@demo.local",
          "van.greer@demo.local",
          "shirley.cook@demo.local",
          "van.greer@demo.local",
          "shirley.cook@demo.local",
          "van.greer@demo.local"
        ],
        "specific_data.data.network_interfaces.ips_preferred": [
          "10.0.50.111"
        ],
        "specific_data.data.last_used_users_mail_association": [
          "shirley.cook@demo.local",
          "van.greer@demo.local"
        ]
      }
    ],
    "device_count": 1,
    "endpoint_url": "https://myaxonius.on.axonius.com"
  },
  "raw": null,
  "inputs": {
    "axonius_write_attachment": false,
    "axonius_field_name_list": "[\"specific_data.data.network_interfaces.ips_preferred\", \"specific_data.data.name\", \"specific_data.data.hostname_preferred\", \"specific_data.data.owner\", \"specific_data.data.last_used_users_mail_association\", \"specific_data.data.os.type_distribution\", \"specific_data.data.last_used_users\", \"specific_data.data.last_used_users_departments_association\", \"specific_data.data.hard_drives.encryption_status\", \"specific_data.data.device_disabled\", \"specific_data.data.network_interfaces.security_level_preferred\", \"specific_data.data.network_interfaces.region_preferred\", \"specific_data.data.network_interfaces.country_preferred\", \"labels\"]",
    "axonius_saved_query_name": null,
    "axonius_query_string": "(\"specific_data.data.hostname\" == \"DESKTOP-shirleyc\")",
    "axonius_incident_id": 2144,
    "axonius_task_id": null,
    "axonius_device_limit": 1
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-axonius",
    "package_version": "1.0.0",
    "host": "mylaptop",
    "execution_time_ms": 24906,
    "timestamp": "2024-03-21 16:41:51"
  }
}

=== ibmresilient/resilient-community-apps/fn_extrahop/payload_samples/funct_extrahop_rx_get_watchlist/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "result": [
      {
        "mod_time": 1681647107939,
        "node_id": 1,
        "id": 4294967313,
        "extrahop_id": "~aws.vpc.ntp----",
        "discovery_id": "~aws.vpc.ntp----",
        "display_name": "aws.vpc.ntp",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158480000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": null,
        "vendor": null,
        "is_l3": false,
        "ipaddr4": null,
        "ipaddr6": null,
        "device_class": "custom",
        "default_name": "Custom ~aws.vpc.ntp----",
        "custom_name": "aws.vpc.ntp",
        "cdp_name": "",
        "dhcp_name": "",
        "netbios_name": "",
        "dns_name": "",
        "custom_type": "",
        "auto_role": "custom",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "custom",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      },
      {
        "mod_time": 1681752256777,
        "node_id": 1,
        "id": 4294967298,
        "extrahop_id": "0e627f3316130000",
        "discovery_id": "0e627f3316130000",
        "display_name": "db1.i.rx.tours",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158510000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": "0E:62:7F:33:16:13",
        "vendor": null,
        "is_l3": false,
        "ipaddr4": "10.1.1.7",
        "ipaddr6": null,
        "device_class": "node",
        "default_name": "Device 0e627f3316130000",
        "custom_name": null,
        "cdp_name": "",
        "dhcp_name": "",
        "netbios_name": "",
        "dns_name": "db1.i.rx.tours",
        "custom_type": "",
        "auto_role": "db_server",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "db_server",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      },
      {
        "mod_time": 1681752406778,
        "node_id": 1,
        "id": 4294967311,
        "extrahop_id": "0e3da802a0b30000",
        "discovery_id": "0e3da802a0b30000",
        "display_name": "pc3",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158480000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": "0E:3D:A8:02:A0:B3",
        "vendor": null,
        "is_l3": false,
        "ipaddr4": "10.1.0.161",
        "ipaddr6": null,
        "device_class": "node",
        "default_name": "Device 0e3da802a0b30000",
        "custom_name": null,
        "cdp_name": "",
        "dhcp_name": "pc3",
        "netbios_name": "PC3",
        "dns_name": "pc3.i.rx.tours",
        "custom_type": "",
        "auto_role": "pc",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "pc",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      },
      {
        "mod_time": 1681752437427,
        "node_id": 1,
        "id": 4294967316,
        "extrahop_id": "0e2c7dd42fa50000",
        "discovery_id": "0e2c7dd42fa50000",
        "display_name": "oasis.i.rx.tours",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158720000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": "0E:2C:7D:D4:2F:A5",
        "vendor": null,
        "is_l3": false,
        "ipaddr4": null,
        "ipaddr6": "2600:1f10:44c7:3304:1bb4:204b:45f3:30a0",
        "device_class": "node",
        "default_name": "Device 0e2c7dd42fa50000",
        "custom_name": null,
        "cdp_name": "",
        "dhcp_name": "",
        "netbios_name": "",
        "dns_name": "oasis.i.rx.tours",
        "custom_type": "",
        "auto_role": "other",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "other",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      },
      {
        "mod_time": 1681752198592,
        "node_id": 1,
        "id": 4294967296,
        "extrahop_id": "0e3332e223c10000",
        "discovery_id": "0e3332e223c10000",
        "display_name": "jump.i.rx.tours",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158450000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": "0E:33:32:E2:23:C1",
        "vendor": null,
        "is_l3": false,
        "ipaddr4": null,
        "ipaddr6": "fe80::c33:32ff:fee2:23c1",
        "device_class": "node",
        "default_name": "Device 0e3332e223c10000",
        "custom_name": null,
        "cdp_name": "",
        "dhcp_name": "",
        "netbios_name": "",
        "dns_name": "jump.i.rx.tours",
        "custom_type": "",
        "auto_role": "other",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "other",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      },
      {
        "mod_time": 1681716728051,
        "node_id": 1,
        "id": 4294967315,
        "extrahop_id": "0e915f41761b0000",
        "discovery_id": "0e915f41761b0000",
        "display_name": "Device 0e915f41761b0000",
        "description": null,
        "user_mod_time": 0,
        "discover_time": 1681158480000,
        "vlanid": 0,
        "parent_id": null,
        "macaddr": "0E:91:5F:41:76:1B",
        "vendor": null,
        "is_l3": false,
        "ipaddr4": "10.1.0.1",
        "ipaddr6": null,
        "device_class": "gateway",
        "default_name": "Device 0e915f41761b0000",
        "custom_name": null,
        "cdp_name": "",
        "dhcp_name": "",
        "netbios_name": "",
        "dns_name": "",
        "custom_type": "",
        "auto_role": "gateway",
        "analysis_level": 2,
        "analysis": "advanced",
        "role": "gateway",
        "on_watchlist": true,
        "last_seen_time": null,
        "model": null,
        "model_override": null,
        "custom_make": null,
        "custom_model": null,
        "critical": false,
        "custom_criticality": null,
        "cloud_instance_id": null,
        "cloud_instance_type": null,
        "cloud_instance_description": null,
        "cloud_instance_name": null,
        "cloud_account": null,
        "vpc_id": null,
        "subnet_id": null
      }
    ]
  },
  "raw": null,
  "inputs": {},
  "metrics": {
    "version": "1.0",
    "package": "fn-extrahop",
    "package_version": "1.0.0",
    "host": "laptop.local",
    "execution_time_ms": 688,
    "timestamp": "2023-04-17 13:27:24"
  }
}
