=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_get_module_activity/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {},
        "properties": {
          "type": "object",
          "properties": {
            "definition": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "type": {},
            "parameterSets": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "parameters": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "isMandatory": {
                          "type": "boolean"
                        },
                        "isDynamic": {
                          "type": "boolean"
                        },
                        "position": {
                          "type": "integer"
                        },
                        "valueFromPipeline": {
                          "type": "boolean"
                        },
                        "valueFromPipelineByPropertyName": {
                          "type": "boolean"
                        },
                        "valueFromRemainingArguments": {
                          "type": "boolean"
                        },
                        "description": {},
                        "validationSet": {
                          "type": "array"
                        }
                      }
                    }
                  }
                }
              }
            },
            "outputTypes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              }
            },
            "creationTime": {
              "type": "string"
            },
            "lastModifiedTime": {
              "type": "string"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "activity_name": {
          "type": "string"
        },
        "account_name": {
          "type": "string"
        },
        "resource_group_name": {
          "type": "string"
        },
        "module_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_salesforce/payload_samples/salesforce_sync_tasks_between_cases/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "task_count_to_salesforce": 1,
    "task_count_to_soar": 0
  },
  "raw": null,
  "inputs": {
    "task_sync_direction": "Salesforce",
    "incident_id": 2199,
    "salesforce_case_id": "500Hr00001Wu3EtIAJ"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-salesforce",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 914,
    "timestamp": "2023-08-08 16:12:06"
  }
}

=== ibmresilient/resilient-community-apps/fn_relations/payload_samples/relations_sync_datatable_data/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "datatables": [
      "email_conversations"
    ],
    "rows": null,
    "incidents": [
      2097
    ]
  },
  "raw": null,
  "inputs": {
    "relations_datatables": "email_conversations",
    "incident_id": 2096,
    "relations_exclude_datatables": "dt_relations_child_incidents"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-relations",
    "package_version": "3.1.0",
    "host": "localhost",
    "execution_time_ms": 1076,
    "timestamp": "2024-01-17 11:23:17"
  }
}

=== ibmresilient/resilient-community-apps/fn_microsoft_sentinel/payload_samples/sentinel_get_incident_alerts/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "value": [
      {
        "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/demoassets/providers/Microsoft.OperationalInsights/workspaces/AzureSentinelDemo/providers/Microsoft.SecurityInsights/Entities/4c4831e9-2ed7-a44a-e530-c784cc7c2ddc",
        "name": "4c4831e9-2ed7-a44a-e530-c784cc7c2ddc",
        "type": "Microsoft.SecurityInsights/Entities",
        "kind": "SecurityAlert",
        "properties": {
          "systemAlertId": "4c4831e9-2ed7-a44a-e530-c784cc7c2ddc",
          "tactics": [
            "PreAttack"
          ],
          "alertDisplayName": "Suspected brute-force attack attempt",
          "description": "Brute-force attack is a common attack technique for finding valid credentials to the database. By submitting many users/passwords combinations, an attacker can guess a correct one.\r\nOnce obtained, an attacker can have full access to the database. While this specific alert doesn't indicate a successful brute-force, it is advised to take safety measures to protect your resource against this attack.\r\nTo investigate this suspected brute-force attempt, review it's origin (based on the application name and IP/Location), and try to find out whether it's recognized to you, or suspicious.\r\nIf you believe this to be an attack on your database, use firewall rules to limit the access to your resource, and make sure you use strong passwords and not well known user names.\r\nAlso, consider using only AAD authentication to further enhance your security posture.\r\n",
          "remediationSteps": [
            "* Apply [workflow automation](https://go.microsoft.com/fwlink/?linkid=2174808) to block future attacks.",
            "* Consider [blocking the IP address](https://go.microsoft.com/fwlink/?linkid=2099055) of the attacking client and hardening your firewall.",
            "* When possible, use [Windows authentication](https://go.microsoft.com/fwlink/?linkid=2129121) and disable SQL Server authentication.",
            "* Use [strong passwords](https://go.microsoft.com/fwlink/?linkid=2099068) and avoid reusing them across multiple databases.",
            "* If applicable, disable default and well known application/database accounts such as SA."
          ],
          "confidenceLevel": "Unknown",
          "severity": "High",
          "vendorName": "Microsoft",
          "productName": "Azure Security Center",
          "productComponentName": "Databases",
          "alertType": "SQL.VM_BruteForce",
          "processingEndTime": "2024-04-10T15:29:40.734843Z",
          "status": "New",
          "endTimeUtc": "2024-04-10T15:29:10Z",
          "startTimeUtc": "2024-04-10T15:29:10Z",
          "timeGenerated": "2024-04-10T15:29:49.9010714Z",
          "compromisedEntity": "PAMSqlSv",
          "providerAlertId": "2516895378499999999_c01aa88b-4520-4c62-a80d-c61f3dfaf47e",
          "alertLink": "https://portal.azure.com/#blade/Microsoft_Azure_Security_AzureDefenderForData/AlertBlade/alertId/2516895378499999999_c01aa88b-4520-4c62-a80d-c61f3dfaf47e/subscriptionId/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroup/DemoAssets/referencedFrom/alertDeepLink/location/centralus",
          "resourceIdentifiers": [
            {
              "type": "AzureResource",
              "resourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/DemoAssets/providers/Microsoft.Compute/virtualMachines/PAMSqlSv",
              "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
            },
            {
              "type": "LogAnalytics",
              "workspaceId": "c6c712b0-dc3d-4408-945a-4bde1db6579b",
              "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
              "agentId": "7db452ea-1cae-4079-94a5-85dc76156e96"
            }
          ],
          "additionalData": {
            "MTP_Classification": "Unknown",
            "StoreAlertPublisher": "{\"Succeeded\":true,\"Reason\":null,\"PublishTime\":\"2024-04-10T15:29:41.6565662Z\"}",
            "AlertMessageEnqueueTime": "2024-04-10T15:29:49.911Z",
            "OriginalProductName": "Azure Security Center",
            "OriginalProductComponentName": "Databases",
            "effectiveSubscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
          },
          "friendlyName": "Suspected brute-force attack attempt",
          "timeGenerated_ms": 1712762989000
        }
      }
    ]
  },
  "raw": null,
  "inputs": {
    "sentinel_incident_id": "b3763ac5-6319-496b-b404-6c5000418a81",
    "sentinel_profile": null,
    "sentinel_label": "label1"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-microsoft-sentinel",
    "package_version": "2.1.0",
    "host": "local",
    "execution_time_ms": 883,
    "timestamp": "2024-04-10 14:07:28"
  }
}

=== ibmresilient/resilient-community-apps/fn_algosec/payload_samples/algosec_traffic_change_request/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "Success",
    "messages": [],
    "data": {
      "changeRequestId": 11,
      "redirectUrl": "https://1.2.3.4/FireFlow/Ticket/Display.html?id=11"
    }
  },
  "raw": null,
  "inputs": {
    "algosec_traffic_change_action": "Drop",
    "algosec_service": "any",
    "algosec_source": "1.1.1.1, any",
    "algosec_traffic_change_request_subject": "IBM SOAR Isolation Request for 1.1.1.1",
    "algosec_destination": "any, 1.1.1.1",
    "algosec_traffic_change_template": "Basic Change Traffic Request",
    "algosec_traffic_change_request_description": "Isolation Request initiated by the IBM SOAR Integration."
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-algosec",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 9129,
    "timestamp": "2024-08-02 09:26:21"
  }
}

=== ibmresilient/resilient-community-apps/fn_pa_panorama/payload_samples/panorama_get_job_status/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "@status": "success",
    "result": {
      "job": {
        "tenq": "2025/01/28 06:54:04",
        "tdeq": "06:54:04",
        "id": "576",
        "user": "admin",
        "type": "CommitAll",
        "status": "FIN",
        "queued": "NO",
        "stoppable": "no",
        "result": "FAIL",
        "tfin": "2025/01/28 06:54:04",
        "description": null,
        "positionInQ": "0",
        "progress": "100",
        "push_type": "shared-policy",
        "dgname": "group1",
        "sched": "None",
        "warnings": null,
        "devices": {
          "entry": {
            "serial-no": "00000000000",
            "devicename": null,
            "multi-vsys": "no",
            "vsys": null,
            "status": "not connected",
            "result": "FAIL",
            "tstart": "06:54:04",
            "tfin": "2025/01/28 06:54:04",
            "details": {
              "msg": "device 00000000000 not connected"
            }
          }
        }
      }
    }
  },
  "raw": null,
  "inputs": {
    "panorama_job_id": 576,
    "panorama_label": "panorama"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-pa-panorama",
    "package_version": "1.6.0",
    "host": "local",
    "execution_time_ms": 530,
    "timestamp": "2025-01-28 10:40:31"
  }
}

=== ibmresilient/resilient-community-apps/fn_ldap_utilities/payload_samples/ldap_utilities_remove_from_groups/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "users_dn": [
      "CN=gerry,CN=Users,DC=dev,DC=co3sys,DC=com"
    ],
    "groups_dn": [
      "CN=Charles-3,CN=Users,DC=dev,DC=co3sys,DC=com"
    ]
  },
  "raw": null,
  "inputs": {
    "ldap_domain_name": "Domain2",
    "ldap_multiple_group_dn": "['CN=Charles-3,CN=Users,DC=dev,DC=co3sys,DC=com']",
    "ldap_multiple_user_dn": "['CN=gerry,CN=Users,DC=dev,DC=co3sys,DC=com']"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-ldap-utilities",
    "package_version": "2.1.0",
    "host": "local",
    "execution_time_ms": 1093,
    "timestamp": "2023-03-30 10:58:09"
  }
}

=== ibmresilient/resilient-community-apps/fn_bmc_helix/payload_samples/helix_close_incident/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "closed": [],
    "skipped": [
      {
        "values": {
          "Request ID": "INC000000000110|INC000000000110",
          "Submitter": "Ian_Agent",
          "Submit Date": "2023-06-22T12:56:30.000+0000",
          "Assignee Login ID": "Sally Agent",
          "Last Modified By": "Ian_Agent",
          "Last Modified Date": "2023-06-22T14:30:49.000+0000",
          "Status": "Resolved",
          "Assignee Groups": "1000000005;'Ian_Agent';",
          "InstanceId": "AGGADOP1EB0FUARWNNYGRWNNYGE04Q",
          "Record ID": "AGGADOP1EB0FUARWNNYGRWNNYGE04Q|AGGADOP1EB0FUARWNNYGRWNNYGE04Q",
          "Vendor Assignee Groups": null,
          "Vendor Assignee Groups_parent": null,
          "Assignee Groups_parent": "",
          "Product Categorization Tier 1": null,
          "Product Categorization Tier 2": null,
          "Product Categorization Tier 3": null,
          "Department": "Customer Service",
          "Site Group": "Amsterdam",
          "Region": "Europe",
          "Product Name": null,
          "Manufacturer": null,
          "Product Model/Version": null,
          "Site": "Amsterdam Support Center",
          "SRAttachment": null,
          "Created_By": null,
          "MaxRetries": null,
          "z1D_Command": null,
          "AccessMode": null,
          "z1D_WorklogDetails": null,
          "z1D_Char02": null,
          "z1D_FormName": null,
          "AppInstanceServer": null,
          "SRInstanceID": "NA",
          "zTmpEventGUID": null,
          "AppInterfaceForm": null,
          "Entry ID": "INC000000000110",
          "z1D_Activity_Type": null,
          "z1D_Summary": null,
          "z1D_Details": null,
          "z1D_Secure_Log": null,
          "z1D_View_Access": null,
          "z2AF_Act_Attachment_1": null,
          "Protocol": null,
          "AppLogin": null,
          "AppPassword": null,
          "PortNumber": null,
          "SRMS Registry Instance ID": "SR0011439CCAD4ec8UQwCkOLAQlQAA",
          "SRMSAOIGuid": null,
          "SRID": null,
          "TemplateID": null,
          "z1D_CommunicationSource": null,
          "z1D_ActivityDate_tab": null,
          "Last _Assigned_Date": null,
          "z1D_AssociationDescription": null,
          "Component_ID": null,
          "mc_ueid": null,
          "cell_name": null,
          "policy_name": null,
          "status_incident": null,
          "status_reason2": null,
          "root_component_id_list": null,
          "root_incident_id_list": null,
          "Impact_OR_Root": null,
          "bOrphanedRoot": null,
          "use_case": null,
          "Needs Attention": null,
          "ClientLocale": null,
          "ServiceCI": null,
          "HPD_CI": null,
          "ServiceCI_ReconID": null,
          "HPD_CI_ReconID": null,
          "z1D_CI_FormName": null,
          "Previous_ServiceCI_ReconID": null,
          "Previous_HPD_CI_ReconID": null,
          "z1D_SR_Instanceid": null,
          "Direct Contact Corporate ID": null,
          "KMSGUID": null,
          "HPD_CI_FormName": null,
          "z1D_InterfaceAction": null,
          "z1D_WorkInfoSubmitter": null,
          "Direct Contact Login ID": null,
          "Customer Login ID": "Ian_Agent",
          "AttachmentSourceFormName": null,
          "AttachmentSourceGUID": null,
          "z1D_ConfirmGroup": null,
          "z1D_CreatedFromBackEndSynchWI": null,
          "InfrastructureEventType": "None",
          "policy_type": null,
          "Chat Session ID": null,
          "Modified Chat Session ID": null,
          "Auto Open Session": null,
          "TimeOfEvent": "2023-06-22T12:56:30.000+0000",
          "FirstWIPDate": null,
          "LastWIPDate": null,
          "Broker Vendor Name": null,
          "NeedsAttentionCCS_Setting": "false",
          "RequestCreatedFromDWP": "No",
          "DWP_SRID": null,
          "DWP_SRInstanceID": null,
          "z1D_COG_AutoSuppGrpPredRule": null,
          "COG_CognSuppGrpComp": null,
          "COG_CognSuppGrpOrg": null,
          "COG_CognSuppGrpName": null,
          "COG_CognSuppGrpID": null,
          "z1D_COG_SuppGrpWorkInfoTag": null,
          "Description": "IBM SOAR Case 2099: Hello World",
          "Company": "Calbro Services",
          "Country": "Netherlands",
          "State Province": "Amsterdam",
          "City": "Schiphol-Rijk",
          "Organization": "Information Technology",
          "Assigned Support Organization": "IT Support",
          "Last Name": "Agent",
          "First Name": "Ian",
          "Middle Initial": null,
          "Contact Client Type": "Office-Based Employee",
          "VIP": "No",
          "Contact Sensitivity": "Standard",
          "Desk Location": null,
          "Mail Station": null,
          "Street": "B Avenue 123",
          "Zip/Postal Code": "1234",
          "Internet E-mail": null,
          "Corporate ID": null,
          "Phone Number": "###",
          "z1D Char01": null,
          "Categorization Tier 1": null,
          "Categorization Tier 2": null,
          "Categorization Tier 3": null,
          "z1D Char02": null,
          "z1D Char03": null,
          "z1D Char04": null,
          "Site ID": "STE_SOLN0002844",
          "z1D Action": null,
          "z1D Integer01": null,
          "Assigned Group ID": "SGP000000000011",
          "Person ID": "PPL000000000118",
          "Contact Company": "Calbro Services",
          "Service Type": "Infrastructure Event",
          "z1D Integer02": null,
          "Status_Reason": "No Further Action Required",
          "Detailed Decription": null,
          "Resolution": "Closed from IBM SOAR",
          "Incident Number": "INC000000000225",
          "Urgency": "2-High",
          "Impact": "3-Moderate/Limited",
          "Priority": "High",
          "Priority Weight": 18,
          "Reported Source": "Systems Management",
          "Assigned Group": "Service Desk",
          "Assignee": "Sally Agent",
          "Assigned Support Company": "Calbro Services",
          "Assigned Group Shift Name": null,
          "Assigned Group Shift ID": null,
          "Owner Support Organization": "IT Support",
          "Number of Attachments": null,
          "Vendor Name": null,
          "Owner Group": "Service Desk",
          "Owner Support Company": "Calbro Services",
          "Owner Group ID": "SGP000000000011",
          "Reported Date": "2023-06-22T12:56:30.000+0000",
          "Responded Date": "2023-06-22T12:56:30.000+0000",
          "Last Acknowledged Date": null,
          "Last Resolved Date": "2023-06-22T14:30:48.000+0000",
          "Closed Date": null,
          "Vendor Ticket Number": null,
          "z1D Permission Group ID": null,
          "z1D Permission Group List": null,
          "z1D Modify All Flag-V": null,
          "Resolution Category": null,
          "Direct Contact Internet E-mail": null,
          "Vendor Organization": null,
          "Vendor Group": null,
          "Vendor Group ID": null,
          "z1D Char27": null,
          "Total Transfers": 1,
          "Resolution Method": null,
          "Resolution Category Tier 2": null,
          "Resolution Category Tier 3": null,
          "Closure Product Category Tier1": null,
          "Closure Product Category Tier2": null,
          "Closure Product Category Tier3": null,
          "Closure Product Name": null,
          "Closure Product Model/Version": null,
          "Closure Manufacturer": null,
          "Estimated Resolution Date": null,
          "Required Resolution DateTime": null,
          "Direct Contact Company": null,
          "Direct Contact Last Name": null,
          "Direct Contact First Name": null,
          "Direct Contact Middle Initial": null,
          "Direct Contact Phone Number": null,
          "Direct Contact Organization": null,
          "Direct Contact Department": null,
          "Direct Contact Region": null,
          "Direct Contact Site Group": null,
          "Direct Contact Site": null,
          "Direct Contact Person ID": null,
          "Direct Contact Street": null,
          "Direct Contact Country": null,
          "Direct Contact State/Province": null,
          "Direct Contact City": null,
          "Direct Contact Zip/Postal Code": null,
          "Direct Contact Time Zone": null,
          "Direct Contact Desk Location": null,
          "Direct Contact Mail Station": null,
          "Direct Contact Location Details": null,
          "Direct Contact Site ID": null,
          "Direct Contact Country Code": null,
          "Direct Contact Area Code": null,
          "Direct Contact Local Number": null,
          "Direct Contact Extension": null
        },
        "_links": {
          "self": [
            {
              "href": "https://bmc.com/api/arsys/v1/entry/HPD:IncidentInterface/INC000000000110%7CINC000000000110"
            }
          ]
        }
      }
    ]
  },
  "raw": null,
  "inputs": {
    "incident_id": 2099,
    "helix_payload": "{\"Status_Reason\": \"Done\"}",
    "bmc_helix_request_id": "INC000000000110|INC000000000110"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-bmc-helix",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 442,
    "timestamp": "2023-06-22 10:31:44"
  }
}

=== ibmresilient/resilient-community-apps/fn_reaqta/payload_samples/reaqta_isolate_machine/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "success": true
  },
  "raw": null,
  "inputs": {
    "reaqta_hive": "rhiveam",
    "reaqta_endpoint_id": "982370521729466368"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-reaqta",
    "package_version": "1.1.0",
    "host": "Henry's IBM 16 inch Macbook Pro",
    "execution_time_ms": 1010,
    "timestamp": "2023-07-10 12:46:41"
  }
}
