=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_get_module_activity/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {},
        "properties": {
          "type": "object",
          "properties": {
            "definition": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "type": {},
            "parameterSets": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "parameters": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "isMandatory": {
                          "type": "boolean"
                        },
                        "isDynamic": {
                          "type": "boolean"
                        },
                        "position": {
                          "type": "integer"
                        },
                        "valueFromPipeline": {
                          "type": "boolean"
                        },
                        "valueFromPipelineByPropertyName": {
                          "type": "boolean"
                        },
                        "valueFromRemainingArguments": {
                          "type": "boolean"
                        },
                        "description": {},
                        "validationSet": {
                          "type": "array"
                        }
                      }
                    }
                  }
                }
              }
            },
            "outputTypes": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string"
                  }
                }
              }
            },
            "creationTime": {
              "type": "string"
            },
            "lastModifiedTime": {
              "type": "string"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "activity_name": {
          "type": "string"
        },
        "account_name": {
          "type": "string"
        },
        "resource_group_name": {
          "type": "string"
        },
        "module_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_algosec/payload_samples/algosec_traffic_change_request_details/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "Success",
    "messages": [],
    "data": {
      "id": 11,
      "fields": [
        {
          "name": "Owner",
          "values": [
            "admin<admin@example.com>"
          ]
        },
        {
          "name": "Workflow",
          "values": [
            "Basic"
          ]
        },
        {
          "name": "Creator",
          "values": [
            "admin<admin@example.com>"
          ]
        },
        {
          "name": "Subject",
          "values": [
            "IBM SOAR Isolation Request for 1.1.1.1"
          ]
        },
        {
          "name": "Ticket Template Name",
          "values": [
            "Basic Change Traffic Request"
          ]
        },
        {
          "name": "Change Request Description",
          "values": [
            "Isolation Request initiated by the IBM SOAR Integration."
          ]
        },
        {
          "name": "LastUpdated",
          "values": [
            "2024-08-02 09:26:26"
          ]
        },
        {
          "name": "Requestor",
          "values": [
            "admin<admin@example.com>"
          ]
        },
        {
          "name": "Form Type",
          "values": [
            "Traffic Change"
          ]
        },
        {
          "name": "status",
          "values": [
            "open"
          ]
        }
      ],
      "originalTraffic": [
        {
          "source": {
            "items": [
              {
                "value": "1.1.1.1"
              },
              {
                "value": "any"
              }
            ]
          },
          "destination": {
            "items": [
              {
                "value": "any"
              },
              {
                "value": "1.1.1.1"
              }
            ]
          },
          "service": {
            "items": [
              {
                "value": "any"
              }
            ]
          },
          "application": {
            "items": [
              {
                "value": "any"
              }
            ]
          },
          "user": {
            "items": [
              {
                "value": "any"
              }
            ]
          },
          "fields": [
            {
              "name": "Requested URL Category",
              "values": [
                "any"
              ]
            }
          ],
          "action": "Drop"
        }
      ],
      "plannedTraffic": [
        {
          "source": {
            "items": [
              {
                "value": "1.1.1.1"
              },
              {
                "value": "any"
              }
            ]
          },
          "destination": {
            "items": [
              {
                "value": "any"
              },
              {
                "value": "1.1.1.1"
              }
            ]
          },
          "service": {
            "items": [
              {
                "value": "*"
              }
            ]
          },
          "application": {
            "items": [
              {
                "value": "any"
              }
            ]
          },
          "user": {
            "items": [
              {
                "value": "any"
              }
            ]
          },
          "fields": [
            {
              "name": "Change URL Category",
              "values": [
                "any"
              ]
            }
          ],
          "action": "Drop"
        }
      ]
    }
  },
  "raw": null,
  "inputs": {
    "algosec_change_request_id": 11
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-algosec",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 8305,
    "timestamp": "2024-08-02 09:26:31"
  }
}

=== ibmresilient/resilient-community-apps/fn_siemplify/payload_samples/siemplify_close_case/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "close_case": true
  },
  "raw": null,
  "inputs": {
    "siemplify_root_cause": "<div class=\"rte\"><div>msg for siemplify</div></div>",
    "siemplify_alert_id": "IBM SOAR Alert 2149_42e7d42f-f307-4f50-8407-98e2eb49f4f3",
    "siemplify_reason": "Inconclusive",
    "siemplify_case_id": 66
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-siemplify",
    "package_version": "1.0.0",
    "host": "Marks-MacBook-Pro.local",
    "execution_time_ms": 626,
    "timestamp": "2022-01-07 14:36:29"
  }
}

=== ibmresilient/resilient-community-apps/fn_pa_panorama/payload_samples/panorama_get_address_groups/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": "",
  "content": {
    "@status": "success",
    "@code": "19",
    "result": {
      "@total-count": "1",
      "@count": "1",
      "entry": [
        {
          "@name": "Blocked Group",
          "@location": "vsys",
          "@vsys": "vsys1",
          "static": {
            "member": [
              "1.2.3.4",
              "42.36.75.4",
              "test.com",
              "1.1.1.1"
            ]
          }
        }
      ]
    }
  },
  "raw": null,
  "inputs": {
    "panorama_name_parameter": "Blocked Group",
    "panorama_location": "vsys",
    "panorama_vsys": "vsys1",
    "panorama_label": "panOS"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-pa-panorama",
    "package_version": "1.5.0",
    "host": "local",
    "execution_time_ms": 3285,
    "timestamp": "2024-08-09 09:01:13"
  }
}

=== ibmresilient/resilient-community-apps/fn_splunk_integration/payload_samples/splunk_add_intel_item/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "message": "Create operation successful.",
    "status": true
  },
  "raw": null,
  "inputs": {
    "splunk_query_param1": "ip",
    "splunk_threat_intel_type": "ip_intel",
    "splunk_label": null,
    "splunk_query_param2": "1.1.1.1"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-splunk-integration",
    "package_version": "1.4.0",
    "host": "local",
    "execution_time_ms": 1115,
    "timestamp": "2023-08-29 09:40:23"
  }
}

=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_delete_schedule/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": "",
  "content": {
    "status": 200
  },
  "raw": null,
  "inputs": {
    "account_name": "automation1",
    "resource_group_name": "demoassets",
    "schedule_name": "tester1324"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-azure-automation-utilities",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 1244,
    "timestamp": "2023-08-24 11:38:33"
  }
}

=== ibmresilient/resilient-community-apps/fn_datatable_utils/payload_samples/dt_utils_create_csv_table/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "data_source": "addresses4.csv",
    "rows_added": 6,
    "rows_with_errors": 0
  },
  "raw": null,
  "inputs": {
    "dt_date_time_format": "%m/%d/%y %H:%M",
    "dt_mapping_table": "{\n  \"hdr_number\": \"number\",\n  \"hdr_text\": \"text\",\n  \"hdr_boolean\": \"boolean\",\n  \"hdr_datetime\": \"datetime\",\n  \"hdr_select\": \"select\",\n  \"hdr_multiselect\": \"multi_select\"\n}",
    "incident_id": 2101,
    "attachment_id": 5,
    "dt_datable_name": "dt_utils_test_data_table",
    "dt_has_headers": true
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-datatable-utils",
    "package_version": "2.0.0",
    "host": "AppTestAllen02241.fyre.ibm.com",
    "execution_time_ms": 2456,
    "timestamp": "2023-06-06 01:02:51"
  }
}

=== ibmresilient/resilient-community-apps/fn_azure_automation_utilities/payload_samples/azure_list_automation_accounts/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "value": [
      {
        "id": "/subscriptions/a4b7e24a-c7aa-4d84-8dae-89e99b336784/resourceGroups/DemoAssets/providers/Microsoft.Automation/automationAccounts/automation1",
        "location": "eastus",
        "name": "automation1",
        "type": "Microsoft.Automation/AutomationAccounts",
        "tags": {
          "client": "sentinel"
        },
        "properties": {
          "creationTime": "2023-04-28T14:04:03.0766667+00:00",
          "lastModifiedTime": "2023-07-21T14:25:01.7+00:00",
          "publicNetworkAccess": true,
          "disableLocalAuth": false
        },
        "identity": {
          "type": "SystemAssigned",
          "principalId": "5c1a54ee-a043-4852-9b87-ed53005d9c62",
          "tenantId": "50ad7d3e-b889-434d-802d-13b87c68047b"
        }
      },
      {
        "id": "/subscriptions/a4b7e24a-c7aa-4d84-8dae-89e99b336784/resourceGroups/DemoAssets/providers/Microsoft.Automation/automationAccounts/testing352",
        "location": "eastus",
        "name": "testing352",
        "type": "Microsoft.Automation/AutomationAccounts",
        "tags": {},
        "properties": {
          "creationTime": "2023-07-25T12:05:22.16+00:00",
          "lastModifiedTime": "2023-07-25T12:05:22.16+00:00",
          "publicNetworkAccess": true,
          "disableLocalAuth": false
        },
        "identity": {
          "type": "SystemAssigned",
          "principalId": "ee616124-e026-4ca0-8c64-d34bae779faf",
          "tenantId": "50ad7d3e-b889-434d-802d-13b87c68047b"
        }
      },
      {
        "id": "/subscriptions/a4b7e24a-c7aa-4d84-8dae-89e99b336784/resourceGroups/DemoAssets/providers/Microsoft.Automation/automationAccounts/tester183",
        "location": "Canada Central",
        "name": "tester183",
        "type": "Microsoft.Automation/AutomationAccounts",
        "tags": {},
        "properties": {
          "creationTime": "2023-07-25T12:12:11.663+00:00",
          "lastModifiedTime": "2023-07-25T12:12:11.663+00:00",
          "publicNetworkAccess": true,
          "disableLocalAuth": false
        }
      }
    ]
  },
  "raw": null,
  "inputs": {},
  "metrics": {
    "version": "1.0",
    "package": "fn-azure-automation-utilities",
    "package_version": "1.0.0",
    "host": "Richards-MBP-2.hsd1.ma.comcast.net",
    "execution_time_ms": 1200,
    "timestamp": "2023-07-28 12:12:31"
  }
}

=== ibmresilient/resilient-community-apps/fn_reaqta/payload_samples/reaqta_create_note/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "note": "{\"notes\":\"Potential APT Detected: powershell.exe\\nIBM SOAR 07/07/2023 21:40:16\\nPotential APT Detected: powershell.exe\\n\\n[SOAR Case - 2131](https://9.30.211.113:443/#incidents/2131)\\nIBM SOAR 07/07/2023 13:40:42\\nPotential APT Detected: powershell.exe\\nIBM SOAR 07/07/2023 21:40:16\\nPotential APT Detected: powershell.exe\\n\\n[SOAR Case - 2131](https://9.30.211.113:443/#incidents/2131)\\n\\n[SOAR Case - 2560](https://9.30.24.113:443/#incidents/2560)\\nIBM SOAR 07/07/2023 13:38:32\\nPotential APT Detected: powershell.exe\\nIBM SOAR 07/07/2023 21:40:16\\nPotential APT Detected: powershell.exe\\n\\n[SOAR Case - 2131](https://9.30.211.113:443/#incidents/2131)\\nIBM SOAR 07/07/2023 13:40:42\\nPotential APT Detected: powershell.exe\\nIBM SOAR 07/07/2023 21:40:16\\nPotential APT Detected: powershell.exe\\n\\n[SOAR Case - 2131](https://9.30.211.113:443/#incidents/2131)\\n\\n[SOAR Case - 2560](https://9.30.24.113:443/#incidents/2560)\\n\\n[SOAR Case - 17024](https://169.44.147.200:443/#incidents/17024)\\nIBM SOAR 10/07/2023 12:46:44\\nEndpoint Machine Isolated\"}"
  },
  "raw": null,
  "inputs": {
    "reaqta_alert_id": "1015597023501484034",
    "reaqta_hive": "rhiveam",
    "reaqta_note": "Endpoint Machine Isolated"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-reaqta",
    "package_version": "1.1.0",
    "host": "Henry's IBM 16 inch Macbook Pro",
    "execution_time_ms": 782,
    "timestamp": "2023-07-10 12:46:44"
  }
}
