=== ibmresilient/resilient-community-apps/fn_jira/payload_samples/jira_open_issue/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "issue_url": {
          "type": "string"
        },
        "issue_url_internal": {
          "type": "string"
        },
        "issue_key": {
          "type": "string"
        },
        "issue": {
          "type": "object",
          "properties": {
            "expand": {
              "type": "string"
            },
            "id": {
              "type": "string"
            },
            "self": {
              "type": "string"
            },
            "key": {
              "type": "string"
            },
            "fields": {
              "type": "object",
              "properties": {
                "statuscategorychangedate": {
                  "type": "string"
                },
                "issuetype": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "iconUrl": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "subtask": {
                      "type": "boolean"
                    },
                    "avatarId": {
                      "type": "integer"
                    },
                    "entityId": {
                      "type": "string"
                    },
                    "hierarchyLevel": {
                      "type": "integer"
                    }
                  }
                },
                "timespent": {},
                "customfield_10030": {},
                "project": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "key": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "projectTypeKey": {
                      "type": "string"
                    },
                    "simplified": {
                      "type": "boolean"
                    },
                    "avatarUrls": {
                      "type": "object",
                      "properties": {
                        "48x48": {
                          "type": "string"
                        },
                        "24x24": {
                          "type": "string"
                        },
                        "16x16": {
                          "type": "string"
                        },
                        "32x32": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "customfield_10031": {},
                "fixVersions": {
                  "type": "array"
                },
                "aggregatetimespent": {},
                "resolution": {},
                "customfield_10035": {},
                "customfield_10027": {},
                "customfield_10028": {},
                "customfield_10029": {},
                "resolutiondate": {},
                "workratio": {
                  "type": "integer"
                },
                "issuerestriction": {
                  "type": "object",
                  "properties": {
                    "issuerestrictions": {
                      "type": "object"
                    },
                    "shouldDisplay": {
                      "type": "boolean"
                    }
                  }
                },
                "watches": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "watchCount": {
                      "type": "integer"
                    },
                    "isWatching": {
                      "type": "boolean"
                    }
                  }
                },
                "lastViewed": {},
                "created": {
                  "type": "string"
                },
                "customfield_10020": {},
                "customfield_10021": {},
                "customfield_10022": {},
                "customfield_10023": {},
                "priority": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "iconUrl": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    }
                  }
                },
                "customfield_10024": {},
                "customfield_10025": {},
                "labels": {
                  "type": "array"
                },
                "customfield_10026": {},
                "customfield_10016": {},
                "customfield_10017": {},
                "customfield_10018": {
                  "type": "object",
                  "properties": {
                    "hasEpicLinkFieldDependency": {
                      "type": "boolean"
                    },
                    "showField": {
                      "type": "boolean"
                    },
                    "nonEditableReason": {
                      "type": "object",
                      "properties": {
                        "reason": {
                          "type": "string"
                        },
                        "message": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "customfield_10019": {
                  "type": "string"
                },
                "timeestimate": {},
                "aggregatetimeoriginalestimate": {},
                "versions": {
                  "type": "array"
                },
                "issuelinks": {
                  "type": "array"
                },
                "assignee": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "accountId": {
                      "type": "string"
                    },
                    "emailAddress": {
                      "type": "string"
                    },
                    "avatarUrls": {
                      "type": "object",
                      "properties": {
                        "48x48": {
                          "type": "string"
                        },
                        "24x24": {
                          "type": "string"
                        },
                        "16x16": {
                          "type": "string"
                        },
                        "32x32": {
                          "type": "string"
                        }
                      }
                    },
                    "displayName": {
                      "type": "string"
                    },
                    "active": {
                      "type": "boolean"
                    },
                    "timeZone": {
                      "type": "string"
                    },
                    "accountType": {
                      "type": "string"
                    }
                  }
                },
                "updated": {
                  "type": "string"
                },
                "status": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "iconUrl": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "statusCategory": {
                      "type": "object",
                      "properties": {
                        "self": {
                          "type": "string"
                        },
                        "id": {
                          "type": "integer"
                        },
                        "key": {
                          "type": "string"
                        },
                        "colorName": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "components": {
                  "type": "array"
                },
                "timeoriginalestimate": {},
                "description": {
                  "type": "string"
                },
                "customfield_10010": {},
                "customfield_10014": {},
                "timetracking": {
                  "type": "object"
                },
                "customfield_10015": {},
                "customfield_10005": {},
                "customfield_10006": {},
                "customfield_10007": {},
                "security": {},
                "customfield_10008": {},
                "customfield_10009": {},
                "aggregatetimeestimate": {},
                "attachment": {
                  "type": "array"
                },
                "summary": {
                  "type": "string"
                },
                "creator": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "accountId": {
                      "type": "string"
                    },
                    "emailAddress": {
                      "type": "string"
                    },
                    "avatarUrls": {
                      "type": "object",
                      "properties": {
                        "48x48": {
                          "type": "string"
                        },
                        "24x24": {
                          "type": "string"
                        },
                        "16x16": {
                          "type": "string"
                        },
                        "32x32": {
                          "type": "string"
                        }
                      }
                    },
                    "displayName": {
                      "type": "string"
                    },
                    "active": {
                      "type": "boolean"
                    },
                    "timeZone": {
                      "type": "string"
                    },
                    "accountType": {
                      "type": "string"
                    }
                  }
                },
                "subtasks": {
                  "type": "array"
                },
                "reporter": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "accountId": {
                      "type": "string"
                    },
                    "emailAddress": {
                      "type": "string"
                    },
                    "avatarUrls": {
                      "type": "object",
                      "properties": {
                        "48x48": {
                          "type": "string"
                        },
                        "24x24": {
                          "type": "string"
                        },
                        "16x16": {
                          "type": "string"
                        },
                        "32x32": {
                          "type": "string"
                        }
                      }
                    },
                    "displayName": {
                      "type": "string"
                    },
                    "active": {
                      "type": "boolean"
                    },
                    "timeZone": {
                      "type": "string"
                    },
                    "accountType": {
                      "type": "string"
                    }
                  }
                },
                "aggregateprogress": {
                  "type": "object",
                  "properties": {
                    "progress": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    }
                  }
                },
                "customfield_10001": {},
                "customfield_10002": {},
                "customfield_10003": {},
                "customfield_10004": {},
                "environment": {},
                "duedate": {},
                "progress": {
                  "type": "object",
                  "properties": {
                    "progress": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    }
                  }
                },
                "comment": {
                  "type": "object",
                  "properties": {
                    "comments": {
                      "type": "array"
                    },
                    "self": {
                      "type": "string"
                    },
                    "maxResults": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "startAt": {
                      "type": "integer"
                    }
                  }
                },
                "votes": {
                  "type": "object",
                  "properties": {
                    "self": {
                      "type": "string"
                    },
                    "votes": {
                      "type": "integer"
                    },
                    "hasVoted": {
                      "type": "boolean"
                    }
                  }
                },
                "worklog": {
                  "type": "object",
                  "properties": {
                    "startAt": {
                      "type": "integer"
                    },
                    "maxResults": {
                      "type": "integer"
                    },
                    "total": {
                      "type": "integer"
                    },
                    "worklogs": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          }
        },
        "jira_dt_name": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "incident_id": {
          "type": "integer"
        },
        "jira_fields": {
          "type": "string"
        },
        "jira_label": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_jira/payload_samples/jira_open_issue/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "issue_url": "https://example.com/browse/JRA-239",
    "issue_url_internal": "https://example.com/rest/api/2/issue/10318",
    "issue_key": "JRA-239",
    "issue": {
      "expand": "renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations,customfield_10010.requestTypePractice",
      "id": "10318",
      "self": "https://example.com/rest/api/2/issue/10318",
      "key": "JRA-239",
      "fields": {
        "statuscategorychangedate": "2023-09-25T15:29:01.286-0400",
        "issuetype": {
          "self": "https://example.com/rest/api/2/issuetype/10007",
          "id": "10007",
          "description": "Stories track functionality or features expressed as user goals.",
          "iconUrl": "https://example.com/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium",
          "name": "Story",
          "subtask": false,
          "avatarId": 10315,
          "entityId": "28f65659-c37e-43ad-a17f-1d00d8d6d9ac",
          "hierarchyLevel": 0
        },
        "timespent": null,
        "customfield_10030": null,
        "customfield_10031": null,
        "project": {
          "self": "https://example.com/rest/api/2/project/10001",
          "id": "10001",
          "key": "JRA",
          "name": "Test Project",
          "projectTypeKey": "software",
          "simplified": true,
          "avatarUrls": {
            "48x48": "https://example.com/rest/api/2/universal_avatar/view/type/project/avatar/10419",
            "24x24": "https://example.com/rest/api/2/universal_avatar/view/type/project/avatar/10419?size=small",
            "16x16": "https://example.com/rest/api/2/universal_avatar/view/type/project/avatar/10419?size=xsmall",
            "32x32": "https://example.com/rest/api/2/universal_avatar/view/type/project/avatar/10419?size=medium"
          }
        },
        "fixVersions": [],
        "aggregatetimespent": null,
        "customfield_10035": null,
        "resolution": null,
        "customfield_10036": null,
        "customfield_10037": null,
        "customfield_10027": null,
        "customfield_10028": null,
        "customfield_10029": null,
        "resolutiondate": null,
        "workratio": -1,
        "lastViewed": null,
        "issuerestriction": {
          "issuerestrictions": {},
          "shouldDisplay": true
        },
        "watches": {
          "self": "https://example.com/rest/api/2/issue/JRA-239/watchers",
          "watchCount": 1,
          "isWatching": true
        },
        "created": "2023-09-25T15:29:00.925-0400",
        "customfield_10020": null,
        "customfield_10021": null,
        "customfield_10022": null,
        "priority": {
          "self": "https://example.com/rest/api/2/priority/4",
          "iconUrl": "https://example.com/images/icons/priorities/low.svg",
          "name": "Low",
          "id": "4"
        },
        "customfield_10023": null,
        "customfield_10024": null,
        "customfield_10025": null,
        "customfield_10026": null,
        "labels": [],
        "customfield_10016": null,
        "customfield_10017": null,
        "customfield_10018": {
          "hasEpicLinkFieldDependency": false,
          "showField": false,
          "nonEditableReason": {
            "reason": "PLUGIN_LICENSE_ERROR",
            "message": "The Parent Link is only available to Jira Premium users."
          }
        },
        "customfield_10019": "0|i000yv:",
        "timeestimate": null,
        "aggregatetimeoriginalestimate": null,
        "versions": [],
        "issuelinks": [],
        "assignee": {
          "self": "https://example.com/rest/api/2/user?accountId=63a069fc8a07cbd184a8258d",
          "accountId": "63a069fc8a07cbd184a8258d",
          "emailAddress": "soar@example.com",
          "avatarUrls": {
            "48x48": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "24x24": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "16x16": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "32x32": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png"
          },
          "displayName": "SOAR",
          "active": true,
          "timeZone": "America/New_York",
          "accountType": "atlassian"
        },
        "updated": "2023-09-25T15:29:01.138-0400",
        "status": {
          "self": "https://example.com/rest/api/2/status/10003",
          "description": "",
          "iconUrl": "https://example.com/",
          "name": "To Do",
          "id": "10003",
          "statusCategory": {
            "self": "https://example.com/rest/api/2/statuscategory/2",
            "id": 2,
            "key": "new",
            "colorName": "blue-gray",
            "name": "To Do"
          }
        },
        "components": [],
        "timeoriginalestimate": null,
        "description": "IBM SOAR Link: https://soar.com:443/#incidents/4037?task_id=2220\n\nCreated in IBM SOAR",
        "customfield_10010": null,
        "customfield_10014": null,
        "customfield_10015": null,
        "timetracking": {},
        "customfield_10005": null,
        "customfield_10006": null,
        "customfield_10007": null,
        "security": null,
        "customfield_10008": null,
        "attachment": [],
        "customfield_10009": null,
        "aggregatetimeestimate": null,
        "summary": "IBM SOAR: test2",
        "creator": {
          "self": "https://example.com/rest/api/2/user?accountId=63a069fc8a07cbd184a8258d",
          "accountId": "63a069fc8a07cbd184a8258d",
          "emailAddress": "soar@example.com",
          "avatarUrls": {
            "48x48": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "24x24": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "16x16": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "32x32": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png"
          },
          "displayName": "SOAR",
          "active": true,
          "timeZone": "America/New_York",
          "accountType": "atlassian"
        },
        "subtasks": [],
        "customfield_10041": null,
        "reporter": {
          "self": "https://example.com/rest/api/2/user?accountId=63a069fc8a07cbd184a8258d",
          "accountId": "63a069fc8a07cbd184a8258d",
          "emailAddress": "soar@example.com",
          "avatarUrls": {
            "48x48": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "24x24": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "16x16": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png",
            "32x32": "https://secure.gravatar.com/avatar/2cfc976767db44422e9281fb012845a2?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FR-1.png"
          },
          "displayName": "SOAR",
          "active": true,
          "timeZone": "America/New_York",
          "accountType": "atlassian"
        },
        "aggregateprogress": {
          "progress": 0,
          "total": 0
        },
        "customfield_10001": null,
        "customfield_10002": null,
        "customfield_10003": null,
        "customfield_10004": null,
        "environment": null,
        "duedate": null,
        "progress": {
          "progress": 0,
          "total": 0
        },
        "votes": {
          "self": "https://example.com/rest/api/2/issue/JRA-239/votes",
          "votes": 0,
          "hasVoted": false
        },
        "comment": {
          "comments": [],
          "self": "https://example.com/rest/api/2/issue/10318/comment",
          "maxResults": 0,
          "total": 0,
          "startAt": 0
        },
        "worklog": {
          "startAt": 0,
          "maxResults": 20,
          "total": 0,
          "worklogs": []
        }
      }
    },
    "jira_dt_name": "jira_task_references"
  },
  "raw": null,
  "inputs": {
    "incident_id": 4037,
    "jira_fields": "{\"project\": \"JRA\", \"issuetype\": \"Story\", \"priority\": {\"name\": \"Low\"}, \"summary\": \"IBM SOAR: test2\", \"description\": \"Created in IBM SOAR\"}",
    "task_id": 2220,
    "jira_label": "my-server"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-jira",
    "package_version": "3.0.3",
    "host": "local",
    "execution_time_ms": 2127,
    "timestamp": "2023-09-25 15:29:01"
  }
}
