=== ibmresilient/resilient-community-apps/fn_bigfix/payload_samples/fn_bigfix_remediation/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "status_message": {
          "type": "string"
        },
        "remediation_date": {
          "type": "string"
        },
        "action_id": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "bigfix_asset_id": {
          "type": "integer"
        },
        "bigfix_incident_id": {
          "type": "integer"
        },
        "bigfix_artifact_value": {
          "type": "string"
        },
        "bigfix_artifact_type": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_bigfix/payload_samples/fn_bigfix_remediation/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "status": "OK",
    "status_message": "BigFix action created successfully.",
    "remediation_date": "08-08-2022 14:06:24",
    "action_id": "48"
  },
  "raw": null,
  "inputs": {
    "bigfix_asset_id": 12315195,
    "bigfix_incident_id": 2111,
    "bigfix_artifact_value": "Run Intel SA-00086 Vulnerability Detection Tool",
    "bigfix_artifact_type": "Process Name"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-bigfix",
    "package_version": "1.2.0",
    "host": "local",
    "execution_time_ms": 412,
    "timestamp": "2022-08-08 14:06:24"
  }
}
