=== ibmresilient/resilient-community-apps/fn_utilities/payload_samples/utilities_call_rest_api/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "ok": {
      "type": "boolean"
    },
    "url": {
      "type": "string"
    },
    "status_code": {
      "type": "integer"
    },
    "reason": {
      "type": "string"
    },
    "cookies": {
      "type": "object"
    },
    "headers": {
      "type": "object",
      "properties": {
        "Date": {
          "type": "string"
        },
        "Content-Type": {
          "type": "string"
        },
        "Content-Length": {
          "type": "string"
        },
        "Connection": {
          "type": "string"
        },
        "Server": {
          "type": "string"
        },
        "Access-Control-Allow-Origin": {
          "type": "string"
        },
        "Access-Control-Allow-Credentials": {
          "type": "string"
        }
      }
    },
    "elapsed": {
      "type": "integer"
    },
    "apparent_encoding": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "json": {
      "type": "object",
      "properties": {
        "args": {
          "type": "object"
        },
        "data": {
          "type": "string"
        },
        "files": {
          "type": "object"
        },
        "form": {
          "type": "object"
        },
        "headers": {
          "type": "object",
          "properties": {
            "Accept": {
              "type": "string"
            },
            "Accept-Encoding": {
              "type": "string"
            },
            "Content-Length": {
              "type": "string"
            },
            "Content-Type": {
              "type": "string"
            },
            "Host": {
              "type": "string"
            },
            "User-Agent": {
              "type": "string"
            },
            "X-Amzn-Trace-Id": {
              "type": "string"
            },
            "X-Frooble": {
              "type": "string"
            }
          }
        },
        "json": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            }
          }
        },
        "origin": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "links": {
      "type": "object"
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_utilities/payload_samples/utilities_call_rest_api/output_json_example.json
{
    "cookies": {
        "__cfduid": "df6a42088e8cb3550f4b3266137fdea731563377650"
    },
    "links": {},
    "text": "{\n  'userId': 1,\n  'id': 1,\n  'title': 'delectus aut autem',\n  'completed': false\n}",
    "elapsed": 263,
    "apparent_encoding": "ascii",
    "reason": "OK",
    "ok": true,
    "url": "https://jsonplaceholder.typicode.com/todos/1",
    "headers": {
        "Expires": "Wed, 17 Jul 2019 19:34:11 GMT",
        "X-Content-Type-Options": "nosniff",
        "X-Powered-By": "Express",
        "Transfer-Encoding": "chunked",
        "Set-Cookie": "__cfduid=df6a42088e8cb3550f4b3266137fdea731563377650; expires=Thu, 16-Jul-20 15:34:10 GMT; path=/; domain=.typicode.com; HttpOnly",
        "CF-Cache-Status": "HIT",
        "Cache-Control": "public, max-age=14400",
        "Vary": "Origin, Accept-Encoding",
        "Content-Encoding": "gzip",
        "Server": "cloudflare",
        "Connection": "keep-alive",
        "Etag": "W/'53-hfEnumeNh6YirfjyjaujcOPPT+s'",
        "Pragma": "no-cache",
        "Access-Control-Allow-Credentials": "true",
        "Date": "Wed, 17 Jul 2019 15:34:11 GMT",
        "CF-RAY": "4f7d474ebce8ce2b-LHR",
        "Content-Type": "application/json; charset=utf-8",
        "Age": "791",
        "Via": "1.1 vegur"
    },
    "json": {
        "completed": false,
        "userId": 1,
        "id": 1,
        "title": "delectus aut autem"
    },
    "status_code": 200
}
