=== ibmresilient/resilient-community-apps/fn_symantec_dlp/payload_samples/symantec_dlp_get_incident_details/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "notes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "editableIncidentDetails": {
          "type": "object",
          "properties": {
            "incidentId": {
              "type": "integer"
            },
            "infoMap": {
              "type": "object",
              "properties": {
                "detectedRemediationStatus": {
                  "type": "integer"
                },
                "preventOrProtectStatusId": {
                  "type": "integer"
                },
                "incidentStatusName": {
                  "type": "string"
                },
                "isHidingNotAllowed": {
                  "type": "boolean"
                },
                "severityId": {
                  "type": "integer"
                },
                "incidentStatusId": {
                  "type": "integer"
                },
                "isHidden": {
                  "type": "boolean"
                }
              }
            },
            "customAttributeGroups": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "nameInternationalized": {
                    "type": "boolean"
                  },
                  "customAttributes": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "index": {
                          "type": "integer"
                        },
                        "displayOrder": {
                          "type": "integer"
                        },
                        "value": {
                          "type": "string"
                        },
                        "email": {
                          "type": "boolean"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "staticIncidentDetails": {
          "type": "object",
          "properties": {
            "incidentId": {
              "type": "integer"
            },
            "infoMap": {
              "type": "object",
              "properties": {
                "messageType": {
                  "type": "string"
                },
                "discoverContentRootPath": {
                  "type": "string"
                },
                "policyName": {
                  "type": "string"
                },
                "discoverMillisSinceFirstSeen": {
                  "type": "integer"
                },
                "detectionServerName": {
                  "type": "string"
                },
                "discoverTargetId": {
                  "type": "integer"
                },
                "discoverName": {
                  "type": "string"
                },
                "fileOwner": {
                  "type": "string"
                },
                "policyVersion": {
                  "type": "integer"
                },
                "discoverServer": {
                  "type": "string"
                },
                "discoverRepositoryLocation": {
                  "type": "string"
                },
                "discoverScanId": {
                  "type": "integer"
                },
                "endpointConnectionStatus": {
                  "type": "string"
                },
                "policyId": {
                  "type": "integer"
                },
                "detectionServerId": {
                  "type": "integer"
                },
                "messageId": {
                  "type": "integer"
                },
                "creationDate": {
                  "type": "string"
                },
                "isBlockedStatusSuperseded": {
                  "type": "boolean"
                },
                "detectionDate": {
                  "type": "string"
                },
                "messageDate": {
                  "type": "string"
                },
                "attachmentInfo": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "messageComponentName": {
                        "type": "string"
                      },
                      "messageComponentId": {
                        "type": "integer"
                      },
                      "wasCracked": {
                        "type": "boolean"
                      },
                      "documentFormat": {
                        "type": "string"
                      },
                      "messageComponentType": {
                        "type": "integer"
                      },
                      "originalSize": {
                        "type": "integer"
                      }
                    }
                  }
                },
                "fileCreateDate": {
                  "type": "string"
                },
                "fileAccessDate": {
                  "type": "string"
                },
                "discoverTargetName": {
                  "type": "string"
                },
                "policyGroupName": {
                  "type": "string"
                },
                "policyGroupId": {
                  "type": "integer"
                },
                "messageSource": {
                  "type": "string"
                },
                "matchCount": {
                  "type": "integer"
                },
                "messageAclEntries": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "cloudStorageCollaborator": {
                        "type": "string"
                      },
                      "aclType": {
                        "type": "string"
                      },
                      "sharepointPermission": {
                        "type": "string"
                      },
                      "cloudstorageRole": {
                        "type": "string"
                      },
                      "grantDeny": {
                        "type": "string"
                      },
                      "sharePointACL": {
                        "type": "string"
                      },
                      "readACLShare": {
                        "type": "string"
                      },
                      "readACLFile": {
                        "type": "string"
                      }
                    }
                  }
                },
                "messageTypeId": {
                  "type": "integer"
                },
                "discoverScanStartDate": {
                  "type": "string"
                },
                "discoverUrl": {
                  "type": "string"
                }
              }
            }
          }
        },
        "sdlp_incident_url": {
          "type": "string"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "sdlp_incident_id": {
          "type": "integer"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_symantec_dlp/payload_samples/symantec_dlp_update_incident/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "success": true,
    "sdlp_incident_id": 481,
    "sdlp_incident_status": "Dismissed",
    "sdlp_incident_severity_id": "Low"
  },
  "raw": null,
  "inputs": {
    "incident_id": 3661,
    "sdlp_incident_status": "Dismissed",
    "sdlp_incident_severity_id": "Info"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-symantec-dlp",
    "package_version": "2.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 15519,
    "timestamp": "2022-04-01 14:47:38"
  }
}

=== ibmresilient/resilient-community-apps/fn_symantec_dlp/payload_samples/symantec_dlp_upload_binaries/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "success": true,
    "artifact_name_list": [
      "c:\\Users\\Administrator\\Documents\\three-ss-one-cc.txt"
    ]
  },
  "raw": null,
  "inputs": {
    "incident_id": 3456,
    "sdlp_incident_id": 578
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-symantec-dlp",
    "package_version": "2.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 9905,
    "timestamp": "2022-03-07 14:10:32"
  }
}
