=== ibmresilient/resilient-community-apps/fn_utilities/payload_samples/utilities_artifact_hash/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "filename": {
      "type": "string"
    },
    "content_type": {
      "type": "string"
    },
    "size": {
      "type": "integer"
    },
    "created": {
      "type": "integer"
    },
    "sha3_512": {
      "type": "string"
    },
    "shake_128": {
      "type": "string"
    },
    "sha256": {
      "type": "string"
    },
    "blake2b": {
      "type": "string"
    },
    "sha3_224": {
      "type": "string"
    },
    "blake2s": {
      "type": "string"
    },
    "md5": {
      "type": "string"
    },
    "sha1": {
      "type": "string"
    },
    "sha224": {
      "type": "string"
    },
    "sha512": {
      "type": "string"
    },
    "shake_256": {
      "type": "string"
    },
    "sha384": {
      "type": "string"
    },
    "sha3_256": {
      "type": "string"
    },
    "sha3_384": {
      "type": "string"
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_soar_utils/payload_samples/soar_utils_attachment_hash/output_json_example.json
{
  "filename": "fn_timer.log",
  "content_type": "application/octet-stream",
  "size": 14094,
  "created": 1663177933110,
  "md5": "d6815ac*******97d87d21b942ed7c96f",
  "sha3_256": "756508e72*******4931e199674e65ff9ba5daa25914f75cca8d424efd7ab89f0d",
  "shake_256": "356ba4b*******6ad64ed936f0d47e7b19022adfcfc236753182f13a82613c87e3b2dc206fb523952d1841837f785dd8bf137d74919253249327dec36a7b4f180a61cd29e2f2db53febac95deee3300519d4dd28ba08af297f29a5862653a314324e78e41fe2696ab25fb42aa80c63556eeb119d961157c0fb573d93953b7adc485e4cee5c3ecc5561acc5d45c2b1ccb5575a28763a877859d11c9f520d311a750314aebbd71e2459caa4d35a799aeee9f285934086f302d94f368ace46def566f6aac8884b5701914ff26f304b072931bbaeb697aa9d11a71d21767924c96ffe5793848aee50cf40d02dfe4f70f6d329cb83d380397f5f4081c1dcb39034458",
  "sha256": "561976be*******478c13ea230e0f6a4e708e3b7befc61642dcd281bcacec975",
  "sha512": "f6f5835*******a1ed7101ae0e21dc3548aab452f5c5d9a634f68c09b50b3ec062f086296628f8d226566637887e5c7be815c83abe2dc8b2746e324b70ac5c",
  "sha3_512": "d3e927*******f00eba36f137565ba945d311f694a40fd8d1998296d41391e7ff9b07269499346ad65bc8f9f27d79b46680b1dc5656ad9e213491c2e1523a",
  "sha1": "44b7ed9da*******ead8977d04a0537fa3125ae",
  "sha3_384": "6324ff6*******b59f0c2f991e0d68f81976b1e85777bb94827ec031a22720dd4b66b12e2576bde798b74a0645",
  "shake_128": "8d64165fb*******aefe04040f8151589fec8fb13e09aeb6ea68e5f5b98ef5032e5233a6463785f1f613e8ba5b0fdb385754845c5f40b6d8f620496366d72709daca6b711ed9646f971e2ad76f78e83077bc8525e8b37610bc6584b96e89439672b093594b541a4c1a9b54bc9b5594d61aaaa3eee7435890cfa9035b820495",
  "blake2s": "9ee3fa9f99*******a7323aaf0bee5a4aa5eb59652911d3cde20567d90f75e",
  "sha3_224": "18f24955d*******f550f52c7bc09d08e423552774674058511cefc",
  "sha224": "d859465ac*******558b6a4856f9517f3ab15ac3b338a96a815af7e",
  "sha384": "83a8bc932*******7c064a809c23aa8d737d2e1844b3c512e912fef14678f43bb0c994250a1d628b06b88075f2b441",
  "blake2b": "26c1297f39*******ebf74e3e5ce49775ba7720f5cce375cabff28cd3b18511a8d9463c1c9f8c85a0cd6d9133b1e5d6486d1054946b2379e4dcafa1d91cc27"
}

=== ibmresilient/resilient-community-apps/fn_utilities/payload_samples/utilities_attachment_hash/output_json_example.json
{
    "sha1": "6c97644ea50f922b8bb2671c772d006b2abf4c87",
    "created": 1563376076661,
    "sha224": "fc76d04a9c02b99e72fd0ec519c1a713ebf4d1ac451cf2542d6c1f9b",
    "filename": "sample_ioc.pdf",
    "sha256": "578711d047bbce6542b5c4f17224d2042ae4ae93a045e0a7b27765f7be226be2",
    "content_type": "application/pdf",
    "sha384": "e6b21c2c6a7bd3e0143bfb8d16e354ccbbbe39df6a586bf6d28443319b4e432816c7a931790f264ac167de6cfd53444e",
    "size": 123852,
    "sha512": "74150483cc49014ff7a83caa2afb71dad62fdb0ec567e4a34fd4fa87a1037b2c5373cc06df0c6ac18e6d399f5bf498e4643c216ad6c7d6b51ab1e506d6768b2a",
    "md5": "fd83928b1530399aa355301ccab3620c"
}

=== ibmresilient/resilient-community-apps/fn_soar_utils/payload_samples/soar_utils_artifact_hash/output_json_example.json
{
  "filename": "fn_timer.log",
  "content_type": "application/octet-stream",
  "size": 14094,
  "created": 1663093337313,
  "blake2b": "26c1297f39175f4b401ebf74e3e5ce49775ba7720f5cce375cabff28cd3b18511a8d9463c1c9f8c85a0cd6d9133b1e5d6486d1054946b2379e4dcafa1d91cc27",
  "md5": "d6815ac62179797d87d21b942ed7c96f",
  "shake_128": "8d64165fb1599e845faefe04040f8151589fec8fb13e09aeb6ea68e5f5b98ef5032e5233a6463785f1f613e8ba5b0fdb385754845c5f40b6d8f620496366d72709daca6b711ed9646f971e2ad76f78e83077bc8525e8b37610bc6584b96e89439672b093594b541a4c1a9b54bc9b5594d61aaaa3eee7435890cfa9035b820495",
  "shake_256": "356ba4b7bc9fda6ad64ed936f0d47e7b19022adfcfc236753182f13a82613c87e3b2dc206fb523952d1841837f785dd8bf137d74919253249327dec36a7b4f180a61cd29e2f2db53febac95deee3300519d4dd28ba08af297f29a5862653a314324e78e41fe2696ab25fb42aa80c63556eeb119d961157c0fb573d93953b7adc485e4cee5c3ecc5561acc5d45c2b1ccb5575a28763a877859d11c9f520d311a750314aebbd71e2459caa4d35a799aeee9f285934086f302d94f368ace46def566f6aac8884b5701914ff26f304b072931bbaeb697aa9d11a71d21767924c96ffe5793848aee50cf40d02dfe4f70f6d329cb83d380397f5f4081c1dcb39034458",
  "sha256": "561976be4b6e992478c13ea230e0f6a4e708e3b7befc61642dcd281bcacec975",
  "sha512": "f6f5835d41d48d27a1ed7101ae0e21dc3548aab452f5c5d9a634f68c09b50b3ec062f086296628f8d226566637887e5c7be815c83abe2dc8b2746e324b70ac5c",
  "sha3_224": "18f24955d1f242a59f550f52c7bc09d08e423552774674058511cefc",
  "sha384": "83a8bc932fc27c3e8f7c064a809c23aa8d737d2e1844b3c512e912fef14678f43bb0c994250a1d628b06b88075f2b441",
  "blake2s": "9ee3fa9f9907f3c6321a7323aaf0bee5a4aa5eb59652911d3cde20567d90f75e",
  "sha3_256": "756508e728338b4931e199674e65ff9ba5daa25914f75cca8d424efd7ab89f0d",
  "sha3_384": "6324ff6f2bfc710a0dfcb59f0c2f991e0d68f81976b1e85777bb94827ec031a22720dd4b66b12e2576bde798b74a0645",
  "sha224": "d859465ac0ccfadba558b6a4856f9517f3ab15ac3b338a96a815af7e",
  "sha1": "44b7ed9daadb3ac89ead8977d04a0537fa3125ae",
  "sha3_512": "d3e927678ab6e0f6f00eba36f137565ba945d311f694a40fd8d1998296d41391e7ff9b07269499346ad65bc8f9f27d79b46680b1dc5656ad9e213491c2e1523a"
}
