=== ibmresilient/resilient-community-apps/fn_playbook_maker/payload_samples/make_playbook/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "playbook_name": {
            "type": "string"
          },
          "success": {
            "type": "boolean"
          },
          "id": {
            "type": "integer"
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "pbm_activation_fields": {
          "type": "boolean"
        },
        "pbm_app_name": {},
        "pbm_playbook_name": {
          "type": "string"
        },
        "pbm_function_names": {
          "type": "string"
        },
        "pbm_activation_type": {
          "type": "string"
        },
        "pbm_playbook_type": {
          "type": "string"
        },
        "pbm_add_to_same_playbook": {
          "type": "boolean"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_playbook_maker/payload_samples/make_playbook/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": [
    {
      "playbook_name": "make-7 for make_playbook",
      "success": true,
      "id": 85
    }
  ],
  "raw": null,
  "inputs": {
    "pbm_activation_fields": false,
    "pbm_app_name": null,
    "pbm_playbook_name": "make-7",
    "pbm_function_names": "make_playbook",
    "pbm_activation_type": "Manual",
    "pbm_playbook_type": "incident",
    "pbm_add_to_same_playbook": false
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-playbook-maker",
    "package_version": "1.0.0",
    "host": "local",
    "execution_time_ms": 5732,
    "timestamp": "2022-06-09 15:12:28"
  }
}
