=== ibmresilient/resilient-community-apps/fn_randori/payload_samples/randori_clear_data_table/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "title": {},
        "message": {},
        "hints": {
          "type": "array"
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "incident_id": {
          "type": "integer"
        },
        "randori_data_table_name": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_randori/payload_samples/randori_get_detections_of_target/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "detection_list": [
      {
        "affiliation_state": "None",
        "applicability": 3,
        "attack_note": "",
        "authority": true,
        "authority_distance": 0,
        "authority_override": false,
        "authorization_state": "None",
        "banners_uuid": null,
        "cert_uuid": "0caabe31-4ede-4e24-9507-f9ebc106951f",
        "characteristic_tags": [
          "DefaultPage",
          "NoCSS",
          "OldCopyright"
        ],
        "characteristics_count": 3,
        "confidence": 75,
        "cpe": {
          "cpe_version": "2.3",
          "edition": null,
          "language": null,
          "other": null,
          "part": "a",
          "product": "tomcat",
          "str": "cpe:2.3:a:apache:tomcat:7.0.76:*:*:*:*:*:*:*",
          "sw_edition": null,
          "target_hw": null,
          "target_sw": null,
          "update": null,
          "vendor": "apache",
          "version": "7.0.76"
        },
        "criticality": 1,
        "deleted": false,
        "description": "Apache Tomcat, often referred to as Tomcat Server, is an open-source Java Servlet Container developed by the Apache Software Foundation.",
        "detection_criteria": {
          "http": {
            "host": "ferrari.demo.webernets.online",
            "method": "GET",
            "path": "/",
            "version": 1.1
          },
          "ip": {
            "address": "34.149.126.94",
            "version": 4
          },
          "tcp": {
            "port": 443
          },
          "tls": {
            "version": 3.3
          }
        },
        "detection_relevance": 1130,
        "enumerability": 3,
        "exploitability": 5,
        "first_seen": "2022-07-07T02:05:22.741389+00:00",
        "headers_uuid": "047cf2ed-c1ff-4bbf-9501-8e0b6b736093",
        "hostname": "ferrari.demo.webernets.online",
        "hostname_id": "82ca6db1-344b-4d12-a7db-5e229e3630d1",
        "id": "f814e5ef-76d9-41c1-b6e8-52b5c0daeb16,5dbcb688-8591-4574-ad18-6cbc27a1941c",
        "impact_score": "Medium",
        "ip": "34.149.126.94",
        "ip_id": "5b3beaa8-d24c-4861-97de-27dc3b5f9bf2",
        "ip_str": "34.149.126.94",
        "last_seen": "2022-10-31T11:22:49.122136+00:00",
        "lens_id": "08a90512-fb94-4766-9cc7-7a945e934638",
        "lens_view": "public",
        "name": "Tomcat",
        "org_id": "923af5dd-50ce-4d80-a55f-707dfe08411e",
        "path": "/",
        "perspective": "00000000-0000-0000-0000-000000000000",
        "perspective_name": "PUBLIC",
        "poc_email": null,
        "poc_id": null,
        "port": 443,
        "post_exploit": 3,
        "priority_impact_factor": 0.084375,
        "priority_score": 135.0,
        "priority_status_factor": 0.1125,
        "priority_tags_factor": 0.253125,
        "private_weakness": 0,
        "protocol": "tcp",
        "public_weakness": 5,
        "randori_notes": "This version of Apache Tomcat has multiple medium and high risk vulnerabilities associated with it including potential remote code execution risks as described in CVE-2020-9484, CVE-2020-1938, and CVE-2019-0232. Apache Tomcat may be vulnerable to the Log4j 2 Remote Code Execution vulnerabilities - CVE-2021-44228 CVE-2021-45046 CVE-2021-45105 CVE-2021-44832 - https://logging.apache.org/log4j/2.x/security.html. Proof-of-Concept exploit code is available for these CVEs. Tomcat does not include Log4J 2 by default, but can be configured to optionally use Log4J 2. Users should check their Log4J 2 configuration and apply mitigations as described in either the above article or per their vendor guidance.",
        "reference": "http://tomcat.apache.org",
        "research": 3,
        "screenshot_uuid": "5afc7cfb-9ab8-4231-a296-909eb7d918e2",
        "service_id": "15d7435d-3469-450f-8ef9-f9e12dde6f68",
        "status": "Needs Investigation",
        "target_confidence": 75,
        "target_first_seen": "2022-07-07T07:18:22.029485+00:00",
        "target_id": "5dbcb688-8591-4574-ad18-6cbc27a1941c",
        "target_last_seen": "2022-10-31T11:32:10.769721+00:00",
        "target_num_detections": 1,
        "target_temptation": 45,
        "tech_category": [
          "App Servers"
        ],
        "temptation_last_modified": "2022-03-31T18:10:37.913851+00:00",
        "thumbnail_uuid": "50adc897-252f-4388-89bb-7ef034b68320",
        "user_tags": [
          "Google",
          "Unknown - By Qualys",
          "Unknown - By Tenable",
          "Wildcard Cert"
        ],
        "vendor": "Apache",
        "version": "7.0.76"
      }
    ]
  },
  "raw": null,
  "inputs": {
    "randori_target_id": "5dbcb688-8591-4574-ad18-6cbc27a1941c"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-randori",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 167,
    "timestamp": "2022-11-02 16:57:13"
  }
}

=== ibmresilient/resilient-community-apps/fn_randori/payload_samples/randori_clear_data_table/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "success": true,
    "title": null,
    "message": null,
    "hints": []
  },
  "raw": null,
  "inputs": {
    "incident_id": 2640,
    "randori_data_table_name": "randori_detections_dt"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-randori",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 10072,
    "timestamp": "2022-11-07 08:18:51"
  }
}

=== ibmresilient/resilient-community-apps/fn_randori/payload_samples/randori_update_target_status/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "count": 1
  },
  "raw": null,
  "inputs": {
    "randori_target_status": "Needs Investigation",
    "randori_target_id": "5dbcb688-8591-4574-ad18-6cbc27a1941c"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-randori",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 190378,
    "timestamp": "2022-11-02 15:52:00"
  }
}

=== ibmresilient/resilient-community-apps/fn_randori/payload_samples/randori_get_paths/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "data": {
      "edges": {
        "329a6ff4-4e2a-4932-b39c-32c5d847e3c0": {
          "content": {},
          "dst": "b4a3b681-c96b-49ba-a0d5-7a576996e703",
          "id": "329a6ff4-4e2a-4932-b39c-32c5d847e3c0",
          "src": "f62ab0f7-954c-4205-a39d-5f170f6131b7",
          "type": "Passive DNS Records"
        },
        "4be17e67-cc0f-4e28-b39f-3844edb09b68": {
          "content": {},
          "dst": "afd6c37d-1280-48ac-bf2d-46ae4286c54b",
          "id": "4be17e67-cc0f-4e28-b39f-3844edb09b68",
          "src": "4be17e67-cc0f-4e28-b39f-3844edb09b68",
          "type": "Detection-Target connection"
        },
        "7d52abd6-f390-4f7b-8312-6367011b1d93": {
          "content": {},
          "dst": "a5f818c5-68c4-40ec-a574-60bfae787651",
          "id": "7d52abd6-f390-4f7b-8312-6367011b1d93",
          "src": "b4a3b681-c96b-49ba-a0d5-7a576996e703",
          "type": "DNS Record"
        },
        "be5f636f-1189-49ee-906c-2a5aff984283": {
          "content": {},
          "dst": "4be17e67-cc0f-4e28-b39f-3844edb09b68",
          "id": "be5f636f-1189-49ee-906c-2a5aff984283",
          "src": "a5f818c5-68c4-40ec-a574-60bfae787651",
          "type": "Port Scan"
        }
      },
      "nodes": {
        "4be17e67-cc0f-4e28-b39f-3844edb09b68": {
          "content": {
            "hostname": "",
            "ip_str": "52.90.36.58",
            "path": "",
            "port": 23,
            "protocol": "tcp"
          },
          "id": "4be17e67-cc0f-4e28-b39f-3844edb09b68",
          "type": "detection"
        },
        "a5f818c5-68c4-40ec-a574-60bfae787651": {
          "content": {
            "ip_str": "52.90.36.58"
          },
          "id": "a5f818c5-68c4-40ec-a574-60bfae787651",
          "type": "ip"
        },
        "afd6c37d-1280-48ac-bf2d-46ae4286c54b": {
          "content": {
            "name": "telnetd",
            "vendor": "Linux",
            "version": ""
          },
          "id": "afd6c37d-1280-48ac-bf2d-46ae4286c54b",
          "type": "target"
        },
        "b4a3b681-c96b-49ba-a0d5-7a576996e703": {
          "content": {
            "hostname": "telnet.webernets.online"
          },
          "id": "b4a3b681-c96b-49ba-a0d5-7a576996e703",
          "type": "hostname"
        },
        "f62ab0f7-954c-4205-a39d-5f170f6131b7": {
          "content": {
            "hostname": "webernets.online"
          },
          "id": "f62ab0f7-954c-4205-a39d-5f170f6131b7",
          "type": "hostname"
        }
      },
      "paths": [
        [
          "4be17e67-cc0f-4e28-b39f-3844edb09b68",
          "be5f636f-1189-49ee-906c-2a5aff984283",
          "7d52abd6-f390-4f7b-8312-6367011b1d93",
          "329a6ff4-4e2a-4932-b39c-32c5d847e3c0"
        ]
      ]
    },
    "base_url": "https://app.randori.io/myorg"
  },
  "raw": null,
  "inputs": {
    "randori_target_id": "afd6c37d-1280-48ac-bf2d-46ae4286c54b"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-randori",
    "package_version": "1.0.0",
    "host": "MacBook-Pro.local",
    "execution_time_ms": 6479,
    "timestamp": "2022-11-09 18:42:30"
  }
}
