=== ibmresilient/resilient-community-apps/fn_ansible_tower/payload_samples/ansible_tower_launch_job_template/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "job": {
          "type": "integer"
        },
        "ignored_fields": {
          "type": "object",
          "properties": {
            "limit": {
              "type": "string"
            }
          }
        },
        "id": {
          "type": "integer"
        },
        "type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "related": {
          "type": "object",
          "properties": {
            "created_by": {
              "type": "string"
            },
            "modified_by": {
              "type": "string"
            },
            "labels": {
              "type": "string"
            },
            "inventory": {
              "type": "string"
            },
            "project": {
              "type": "string"
            },
            "organization": {
              "type": "string"
            },
            "credentials": {
              "type": "string"
            },
            "unified_job_template": {
              "type": "string"
            },
            "stdout": {
              "type": "string"
            },
            "job_events": {
              "type": "string"
            },
            "job_host_summaries": {
              "type": "string"
            },
            "activity_stream": {
              "type": "string"
            },
            "notifications": {
              "type": "string"
            },
            "create_schedule": {
              "type": "string"
            },
            "job_template": {
              "type": "string"
            },
            "cancel": {
              "type": "string"
            },
            "relaunch": {
              "type": "string"
            }
          }
        },
        "summary_fields": {
          "type": "object",
          "properties": {
            "organization": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              }
            },
            "inventory": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "has_active_failures": {
                  "type": "boolean"
                },
                "total_hosts": {
                  "type": "integer"
                },
                "hosts_with_active_failures": {
                  "type": "integer"
                },
                "total_groups": {
                  "type": "integer"
                },
                "has_inventory_sources": {
                  "type": "boolean"
                },
                "total_inventory_sources": {
                  "type": "integer"
                },
                "inventory_sources_with_failures": {
                  "type": "integer"
                },
                "organization_id": {
                  "type": "integer"
                },
                "kind": {
                  "type": "string"
                }
              }
            },
            "project": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "status": {
                  "type": "string"
                },
                "scm_type": {
                  "type": "string"
                },
                "allow_override": {
                  "type": "boolean"
                }
              }
            },
            "job_template": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                }
              }
            },
            "unified_job_template": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "unified_job_type": {
                  "type": "string"
                }
              }
            },
            "created_by": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "username": {
                  "type": "string"
                },
                "first_name": {
                  "type": "string"
                },
                "last_name": {
                  "type": "string"
                }
              }
            },
            "modified_by": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "integer"
                },
                "username": {
                  "type": "string"
                },
                "first_name": {
                  "type": "string"
                },
                "last_name": {
                  "type": "string"
                }
              }
            },
            "user_capabilities": {
              "type": "object",
              "properties": {
                "delete": {
                  "type": "boolean"
                },
                "start": {
                  "type": "boolean"
                }
              }
            },
            "labels": {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "results": {
                  "type": "array"
                }
              }
            },
            "credentials": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "kind": {
                    "type": "string"
                  },
                  "cloud": {
                    "type": "boolean"
                  }
                }
              }
            }
          }
        },
        "created": {
          "type": "string"
        },
        "modified": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "job_type": {
          "type": "string"
        },
        "inventory": {
          "type": "integer"
        },
        "project": {
          "type": "integer"
        },
        "playbook": {
          "type": "string"
        },
        "scm_branch": {
          "type": "string"
        },
        "forks": {
          "type": "integer"
        },
        "limit": {
          "type": "string"
        },
        "verbosity": {
          "type": "integer"
        },
        "extra_vars": {
          "type": "string"
        },
        "job_tags": {
          "type": "string"
        },
        "force_handlers": {
          "type": "boolean"
        },
        "skip_tags": {
          "type": "string"
        },
        "start_at_task": {
          "type": "string"
        },
        "timeout": {
          "type": "integer"
        },
        "use_fact_cache": {
          "type": "boolean"
        },
        "organization": {
          "type": "integer"
        },
        "unified_job_template": {
          "type": "integer"
        },
        "launch_type": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "execution_environment": {},
        "failed": {
          "type": "boolean"
        },
        "started": {},
        "finished": {},
        "canceled_on": {},
        "elapsed": {
          "type": "number"
        },
        "job_args": {
          "type": "string"
        },
        "job_cwd": {
          "type": "string"
        },
        "job_env": {
          "type": "object"
        },
        "job_explanation": {
          "type": "string"
        },
        "execution_node": {
          "type": "string"
        },
        "controller_node": {
          "type": "string"
        },
        "result_traceback": {
          "type": "string"
        },
        "event_processing_finished": {
          "type": "boolean"
        },
        "launched_by": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "work_unit_id": {},
        "job_template": {
          "type": "integer"
        },
        "passwords_needed_to_start": {
          "type": "array"
        },
        "allow_simultaneous": {
          "type": "boolean"
        },
        "artifacts": {
          "type": "object"
        },
        "scm_revision": {
          "type": "string"
        },
        "instance_group": {},
        "diff_mode": {
          "type": "boolean"
        },
        "job_slice_number": {
          "type": "integer"
        },
        "job_slice_count": {
          "type": "integer"
        },
        "webhook_service": {
          "type": "string"
        },
        "webhook_credential": {},
        "webhook_guid": {
          "type": "string"
        }
      }
    },
    "raw": {
      "type": "string"
    },
    "inputs": {
      "type": "object",
      "properties": {
        "tower_skip_tags": {},
        "tower_arguments": {},
        "tower_hosts": {
          "type": "string"
        },
        "tower_template_id": {
          "type": "integer"
        },
        "tower_run_tags": {}
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_qradar_integration/payload_samples/qradar_reference_table_delete_item/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "status_code": 200,
    "content": {
      "time_to_live": "0 years 1 mons 0 days 0 hours 0 mins 0.0 secs",
      "timeout_type": "LAST_SEEN",
      "number_of_elements": 5,
      "creation_time": 1637336107774,
      "name": "Generated_Cases",
      "namespace": "SHARED",
      "element_type": "ALN",
      "collection_id": 51,
      "key_label": "offense_id"
    }
  },
  "raw": "{\"status_code\": 200, \"content\": {\"time_to_live\": \"0 years 1 mons 0 days 0 hours 0 mins 0.0 secs\", \"timeout_type\": \"LAST_SEEN\", \"number_of_elements\": 5, \"creation_time\": 1637336107774, \"name\": \"Generated_Cases\", \"namespace\": \"SHARED\", \"element_type\": \"ALN\", \"collection_id\": 51, \"key_label\": \"offense_id\"}}",
  "inputs": {
    "qradar_reference_table_item_value": "test4",
    "qradar_reference_table_item_inner_key": "457",
    "qradar_reference_table_item_outer_key": "463",
    "qradar_reference_table_name": "Generated_Cases",
    "qradar_label": "SOAR_Plugin_Destination_Name"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-qradar-integration",
    "package_version": "2.2.0",
    "execution_time_ms": 425,
    "timestamp": "2022-01-28 13:19:18"
  }
}

=== ibmresilient/resilient-community-apps/fn_greynoise/payload_samples/greynoise_ip_query_community/output_json_example.json
{
    "version": "1.0",
    "success": true,
    "reason": null,
    "content": {
        "ip": "210.68.105.68",
        "noise": true,
        "riot": false,
        "classification": "malicious",
        "name": "unknown",
        "link": "https://viz.greynoise.io/ip/210.68.105.68",
        "last_seen": "2025-03-04",
        "message": "Success"
    },
    "raw": "",
    "inputs": {
        "greynoise_value": "210.68.105.68",
        "greynoise_type": "community"
    },
    "metrics": {
        "version": "1.0",
        "package": "fn-greynoise",
        "package_version": "1.1.0",
        "host": "localhost",
        "execution_time_ms": 180,
        "timestamp": "2025-03-20 14:32:23"
    }
}

=== ibmresilient/resilient-community-apps/fn_isitphishing/payload_samples/isitphishing_html_document/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "result": "unknown"
  },
  "raw": "",
  "inputs": {
    "incident_id": 3102,
    "attachment_id": 34,
    "filename": "Test URL.txt"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-isitphishing",
    "package_version": "1.2.0",
    "host": "my.app.host",
    "execution_time_ms": 3397,
    "timestamp": "2025-05-15 11:03:49"
  }
}

=== ibmresilient/resilient-community-apps/fn_log_capture/payload_samples/fn_log_capture/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "attachment_name": "li-b6f3814c-2cf7-11b2-a85c-95da948e58bf_resilient-circuits_20250502_132601.log",
    "num_of_lines": 58
  },
  "raw": "",
  "inputs": {
    "log_min_level": "Error",
    "log_attachment_name": null,
    "incident_id": 3102,
    "log_capture_maxlen": null,
    "log_capture_date": null,
    "log_capture_date_option": null
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-log-capture",
    "package_version": "1.0.1",
    "host": "my.app.host",
    "execution_time_ms": 1471,
    "timestamp": "2025-05-02 13:26:03"
  }
}

=== ibmresilient/resilient-community-apps/fn_task_utils/payload_samples/task_utils_update_task/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "task_id": 302,
    "task": {
      "name": "Sample_task",
      "inc_id": 2117,
      "inc_owner_id": 5,
      "due_date": null,
      "required": false,
      "owner_id": null,
      "user_notes": null,
      "status": "O",
      "frozen": false,
      "owner_fname": null,
      "owner_lname": null,
      "init_date": 1751637144637,
      "active": true,
      "src_name": null,
      "inc_name": "Test_task_utils",
      "instr_text": "Close out this required Task",
      "instructions": "Close out this required Task",
      "form": null,
      "members": null,
      "perms": {
        "read": true,
        "write": true,
        "comment": true,
        "assign": true,
        "close": true,
        "change_members": true,
        "attach_file": true,
        "read_attachments": true,
        "delete_attachments": true,
        "change_header": false
      },
      "notes": [],
      "closed_date": null,
      "actions": [
        {
          "id": 121,
          "name": "Example: Task Utils - Make this Task Optional",
          "enabled": true
        }
      ],
      "playbooks": [
        {
          "playbook_handle": 53,
          "display_name": "Task Utils: Mark Task as Optional - Example (PB)"
        }
      ],
      "phase_id": 1009,
      "category_id": null,
      "notes_count": 1,
      "attachments_count": 0,
      "task_layout": [],
      "auto_deactivate": true,
      "creator_principal": {
        "id": 5,
        "type": "user",
        "name": "admin@example.com",
        "display_name": "admin example"
      },
      "timeframe_name": null,
      "regs": {},
      "custom": true,
      "id": 302,
      "inc_training": false,
      "cat_name": "Initial",
      "description": null,
      "at_id": null,
      "private": null
    }
  },
  "raw": "",
  "inputs": {
    "task_name": "Sample_task",
    "task_utils_payload": {
      "format": "text",
      "content": "{\"required\": false}"
    },
    "incident_id": 2117,
    "task_id": 302
  },
  "metrics": {
    "version": "1.0",
    "package": "unknown",
    "package_version": "unknown",
    "host": "my.app.host",
    "execution_time_ms": 2105,
    "timestamp": "2025-07-04 14:53:51"
  }
}

=== ibmresilient/resilient-community-apps/fn_phish_tank/payload_samples/fn_phish_tank_submit_url/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "meta": {
      "timestamp": "2024-11-14T15:01:10+00:00",
      "serverid": "e5f3084e",
      "status": "success",
      "requestid": "172.17.128.1.673610b6b42867.38342693",
      "timestamp_modified": 1731596470000
    },
    "results": {
      "url": "https://ld-procedura.info/sut-mpar-e/",
      "in_database": true,
      "phish_id": 8852101,
      "phish_detail_page": "http://www.phishtank.com/phish_detail.php?phish_id=8852101",
      "verified": false,
      "verified_at": null,
      "valid": false
    }
  },
  "raw": "{\"meta\": {\"timestamp\": \"2024-11-14T15:01:10+00:00\", \"serverid\": \"e5f3084e\", \"status\": \"success\", \"requestid\": \"172.17.128.1.673610b6b42867.38342693\", \"timestamp_modified\": 1731596470000}, \"results\": {\"url\": \"https://ld-procedura.info/sut-mpar-e/\", \"in_database\": true, \"phish_id\": 8852101, \"phish_detail_page\": \"http://www.phishtank.com/phish_detail.php?phish_id=8852101\", \"verified\": false, \"verified_at\": null, \"valid\": false}}",
  "inputs": {
    "phish_tank_check_url": "https://ld-procedura.info/sut-mpar-e/"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-phish-tank",
    "package_version": "1.0.2",
    "host": "my.app.host",
    "execution_time_ms": 140,
    "timestamp": "2024-11-14 10:01:10"
  }
}

=== ibmresilient/resilient-community-apps/fn_task_utils/payload_samples/task_utils_close_task/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "task_id": 302,
    "task_name": "Sample_task"
  },
  "raw": "",
  "inputs": {
    "task_name": "Sample_task",
    "incident_id": 2117
  },
  "metrics": {
    "version": "1.0",
    "package": "unknown",
    "package_version": "unknown",
    "host": "my.app.host",
    "execution_time_ms": 1815,
    "timestamp": "2025-07-04 14:54:21"
  }
}

=== ibmresilient/resilient-community-apps/fn_exchange_online/payload_samples/exchange_online_move_message_to_folder/output_json_example.json
{
  "version": "1.0",
  "success": true,
  "reason": null,
  "content": {
    "new_message_id": "AAMkAGVhZGFlNDVhLTI0MDAtNGE1Ni05Zjk3LTAxNzllYjFiNDAzYwBGAAAAAADG92SqC8zpQJ1GSk2scH2NBwDi5Xky9KHuQ48Uewaxv-e8AAAAAAETAADi5Xky9KHuQ48Uewaxv-e8AAApGtroAAA=",
    "new_web_link": "https://outlook.office365.com/owa/?ItemID=AAMkAGVhZGFlNDVhLTI0MDAtNGE1Ni05Zjk3LTAxNzllYjFiNDAzYwBGAAAAAADG92SqC8zpQJ1GSk2scH2NBwDi5Xky9KHuQ48Uewaxv%2Fe8AAAAAAETAADi5Xky9KHuQ48Uewaxv%2Fe8AAApGtroAAA%3D&exvsurl=1&viewmodel=ReadMessageItem"
  },
  "raw": "{\"new_message_id\": \"AAMkAGVhZGFlNDVhLTI0MDAtNGE1Ni05Zjk3LTAxNzllYjFiNDAzYwBGAAAAAADG92SqC8zpQJ1GSk2scH2NBwDi5Xky9KHuQ48Uewaxv-e8AAAAAAETAADi5Xky9KHuQ48Uewaxv-e8AAApGtroAAA=\", \"new_web_link\": \"https://outlook.office365.com/owa/?ItemID=AAMkAGVhZGFlNDVhLTI0MDAtNGE1Ni05Zjk3LTAxNzllYjFiNDAzYwBGAAAAAADG92SqC8zpQJ1GSk2scH2NBwDi5Xky9KHuQ48Uewaxv%2Fe8AAAAAAETAADi5Xky9KHuQ48Uewaxv%2Fe8AAApGtroAAA%3D&exvsurl=1&viewmodel=ReadMessageItem\"}",
  "inputs": {
    "exo_mailfolders_id": null,
    "exo_email_address": "soartester@reshydradev.onmicrosoft.com",
    "exo_destination_mailfolder_id": {
      "id": 185,
      "name": "archive"
    },
    "exo_messages_id": "AAMkAGVhZGFlNDVhLTI0MDAtNGE1Ni05Zjk3LTAxNzllYjFiNDAzYwBGAAAAAADG92SqC8zpQJ1GSk2scH2NBwDi5Xky9KHuQ48Uewaxv-e8AAAAAAEMAADi5Xky9KHuQ48Uewaxv-e8AAApGgUhAAA="
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-exchange-online",
    "package_version": "1.4.0",
    "host": "Henry's IBM 16 inch Macbook Pro",
    "execution_time_ms": 1043,
    "timestamp": "2023-05-30 15:55:21"
  }
}
