=== ibmresilient/resilient-community-apps/fn_vmware_cbc/payload_samples/vmware_cbc_get_device_by_id/output_json_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "type": "object",
  "properties": {
    "version": {
      "type": "number"
    },
    "success": {
      "type": "boolean"
    },
    "reason": {},
    "content": {
      "type": "object",
      "properties": {
        "device": {
          "type": "object",
          "properties": {
            "activation_code": {},
            "activation_code_expiry_time": {
              "type": "string"
            },
            "appliance_name": {},
            "appliance_uuid": {},
            "auto_scaling_group_name": {},
            "av_ave_version": {},
            "av_engine": {},
            "av_last_scan_time": {},
            "av_pack_version": {},
            "av_product_version": {},
            "av_vdf_version": {},
            "cloud_provider_account_id": {},
            "cloud_provider_resource_id": {},
            "cluster_name": {},
            "compliance_status": {
              "type": "string"
            },
            "current_sensor_policy_name": {
              "type": "string"
            },
            "datacenter_name": {},
            "deployment_type": {
              "type": "string"
            },
            "deregistered_time": {},
            "device_meta_data_item_list": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "key_name": {
                    "type": "string"
                  },
                  "key_value": {
                    "type": "string"
                  },
                  "position": {
                    "type": "integer"
                  }
                }
              }
            },
            "email": {
              "type": "string"
            },
            "esx_host_name": {},
            "esx_host_uuid": {},
            "first_name": {},
            "infrastructure_provider": {
              "type": "string"
            },
            "last_contact_time": {
              "type": "string"
            },
            "last_device_policy_changed_time": {},
            "last_device_policy_requested_time": {
              "type": "string"
            },
            "last_internal_ip_address": {
              "type": "string"
            },
            "last_external_ip_address": {
              "type": "string"
            },
            "last_location": {
              "type": "string"
            },
            "last_policy_updated_time": {
              "type": "string"
            },
            "last_name": {},
            "last_reported_time": {
              "type": "string"
            },
            "last_reset_time": {},
            "last_shutdown_time": {
              "type": "string"
            },
            "login_user_name": {
              "type": "string"
            },
            "mac_address": {
              "type": "string"
            },
            "middle_name": {},
            "name": {
              "type": "string"
            },
            "nsx_distributed_firewall_policy": {},
            "organization_name": {
              "type": "string"
            },
            "os": {
              "type": "string"
            },
            "os_version": {
              "type": "string"
            },
            "policy_name": {
              "type": "string"
            },
            "registered_time": {
              "type": "string"
            },
            "scan_last_action_time": {},
            "scan_last_complete_time": {},
            "scan_status": {},
            "sensor_kit_type": {
              "type": "string"
            },
            "sensor_version": {
              "type": "string"
            },
            "status": {
              "type": "string"
            },
            "sensor_gateway_url": {},
            "sensor_gateway_uuid": {},
            "target_priority": {
              "type": "string"
            },
            "uninstall_code": {
              "type": "string"
            },
            "vcenter_host_url": {},
            "vcenter_name": {},
            "vcenter_uuid": {},
            "virtual_private_cloud_id": {},
            "virtualization_provider": {
              "type": "string"
            },
            "vm_ip": {},
            "vm_uuid": {},
            "vm_name": {},
            "vulnerability_severity": {
              "type": "string"
            },
            "vdi_provider": {
              "type": "string"
            },
            "windows_platform": {},
            "sensor_states": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "cloud_provider_tags": {
              "type": "array"
            },
            "av_status": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "av_update_servers": {},
            "vulnerability_score": {
              "type": "number"
            },
            "id": {
              "type": "integer"
            },
            "ad_group_id": {
              "type": "integer"
            },
            "organization_id": {
              "type": "integer"
            },
            "policy_id": {
              "type": "integer"
            },
            "device_owner_id": {
              "type": "integer"
            },
            "golden_device_id": {},
            "vdi_base_device": {},
            "passive_mode": {
              "type": "boolean"
            },
            "nsx_enabled": {},
            "golden_device": {},
            "base_device": {},
            "av_master": {
              "type": "boolean"
            },
            "virtual_machine": {
              "type": "boolean"
            },
            "sensor_out_of_date": {
              "type": "boolean"
            },
            "sensor_pending_update": {
              "type": "boolean"
            },
            "policy_override": {
              "type": "boolean"
            },
            "quarantined": {
              "type": "boolean"
            },
            "asset_group": {
              "type": "array"
            }
          }
        }
      }
    },
    "raw": {},
    "inputs": {
      "type": "object",
      "properties": {
        "vmware_cbc_device_id": {
          "type": "string"
        }
      }
    },
    "metrics": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "package": {
          "type": "string"
        },
        "package_version": {
          "type": "string"
        },
        "host": {
          "type": "string"
        },
        "execution_time_ms": {
          "type": "integer"
        },
        "timestamp": {
          "type": "string"
        }
      }
    }
  }
}

=== ibmresilient/resilient-community-apps/fn_vmware_cbc/payload_samples/vmware_cbc_post_note_to_cbc_alert/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "author": "FR6K2KN2K",
    "create_timestamp": "2024-04-26T20:30:03.905Z",
    "last_update_timestamp": "2024-04-26T20:30:03.905Z",
    "id": "50c323c1-8495-4fe4-815f-7bc411976ec9",
    "source": "CUSTOMER",
    "note": "Created by IBM SOAR:  VMware CBC Update Case on Creation:  populated Process data table 2  artifact(s) added to the case.",
    "note_json_format": null
  },
  "raw": null,
  "inputs": {
    "vmware_cbc_alert_note_text": "<b>VMware CBC Update Case on Creation:</b> populated Process data table<br /><b>2</b> artifact(s) added to the case.",
    "vmware_cbc_alert_id": "0730b7bc-7d51-9d64-68b1-d3e01d28a716"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-vmware-cbc",
    "package_version": "1.0.0",
    "host": "myapphost",
    "execution_time_ms": 19794,
    "timestamp": "2024-04-26 16:30:04"
  }
}

=== ibmresilient/resilient-community-apps/fn_vmware_cbc/payload_samples/vmware_cbc_post_device_action/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "device_status": "success"
  },
  "raw": null,
  "inputs": {
    "vmware_cbc_device_action": "QUARANTINE",
    "vmware_cbc_device_id": "212389492",
    "vmware_cbc_device_toggle": "OFF"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-vmware-cbc",
    "package_version": "1.0.0",
    "host": "my.app.host",
    "execution_time_ms": 54545,
    "timestamp": "2024-05-31 12:31:34"
  }
}

=== ibmresilient/resilient-community-apps/fn_vmware_cbc/payload_samples/vmware_cbc_get_cbc_notes/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "count": 1
  },
  "raw": null,
  "inputs": {
    "vmware_cbc_note_type": "alert",
    "vmware_cbc_incident_id": 2186,
    "vmware_cbc_id": "0730b7bc-7d51-9d64-68b1-d3e01d28a716"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-vmware-cbc",
    "package_version": "1.0.0",
    "host": "myapphost.com",
    "execution_time_ms": 56753,
    "timestamp": "2024-04-24 16:15:57"
  }
}

=== ibmresilient/resilient-community-apps/fn_vmware_cbc/payload_samples/vmware_cbc_get_device_by_id/output_json_example.json
{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "device": {
      "activation_code": null,
      "activation_code_expiry_time": "2024-04-22T19:31:18.358Z",
      "appliance_name": null,
      "appliance_uuid": null,
      "auto_scaling_group_name": null,
      "av_ave_version": null,
      "av_engine": null,
      "av_last_scan_time": null,
      "av_pack_version": null,
      "av_product_version": null,
      "av_vdf_version": null,
      "cloud_provider_account_id": null,
      "cloud_provider_resource_id": null,
      "cluster_name": null,
      "compliance_status": "NOT_ASSESSED",
      "current_sensor_policy_name": "Standard",
      "datacenter_name": null,
      "deployment_type": "ENDPOINT",
      "deregistered_time": null,
      "device_meta_data_item_list": [
        {
          "key_name": "OS_MAJOR_VERSION",
          "key_value": "Windows 11",
          "position": 0
        },
        {
          "key_name": "SUBNET",
          "key_value": "9.30.43.0",
          "position": 0
        }
      ],
      "email": "Administrator",
      "esx_host_name": null,
      "esx_host_uuid": null,
      "first_name": null,
      "infrastructure_provider": "NONE",
      "last_contact_time": "2024-05-10T17:31:19.521Z",
      "last_device_policy_changed_time": null,
      "last_device_policy_requested_time": "2024-05-10T17:06:42.474Z",
      "last_internal_ip_address": "9.35.43.10",
      "last_external_ip_address": "70.25.23.23",
      "last_location": "OFFSITE",
      "last_policy_updated_time": "2023-12-13T07:03:23.711Z",
      "last_name": null,
      "last_reported_time": "2024-05-10T17:11:52.177Z",
      "last_reset_time": null,
      "last_shutdown_time": "2024-05-10T17:06:03.515Z",
      "login_user_name": "WINSERVER2022\\Administrator",
      "mac_address": "00000a0b67eb",
      "middle_name": null,
      "name": "winserver2022",
      "nsx_distributed_firewall_policy": null,
      "organization_name": "myorg.com",
      "os": "WINDOWS",
      "os_version": "Windows Server 2022 x64",
      "policy_name": "Standard",
      "registered_time": "2024-05-10T16:59:59.563Z",
      "scan_last_action_time": null,
      "scan_last_complete_time": null,
      "scan_status": null,
      "sensor_kit_type": "WINDOWS",
      "sensor_version": "4.0.1.1428",
      "status": "REGISTERED",
      "sensor_gateway_url": null,
      "sensor_gateway_uuid": null,
      "target_priority": "MEDIUM",
      "uninstall_code": "XXXX",
      "vcenter_host_url": null,
      "vcenter_name": null,
      "vcenter_uuid": null,
      "virtual_private_cloud_id": null,
      "virtualization_provider": "OTHER",
      "vm_ip": null,
      "vm_uuid": null,
      "vm_name": null,
      "vulnerability_severity": "IMPORTANT",
      "vdi_provider": "NONE",
      "windows_platform": null,
      "sensor_states": [
        "ACTIVE",
        "LIVE_RESPONSE_NOT_RUNNING",
        "LIVE_RESPONSE_NOT_KILLED",
        "LIVE_RESPONSE_DISABLED",
        "CB_FIREWALL_INACTIVE"
      ],
      "cloud_provider_tags": [],
      "av_status": [
        "AV_ACTIVE",
        "ONDEMAND_SCAN_DISABLED"
      ],
      "av_update_servers": null,
      "vulnerability_score": 8.8,
      "id": 210476652,
      "ad_group_id": 0,
      "organization_id": 72676,
      "policy_id": 493371,
      "device_owner_id": 16421859,
      "golden_device_id": null,
      "vdi_base_device": null,
      "passive_mode": false,
      "nsx_enabled": null,
      "golden_device": null,
      "base_device": null,
      "av_master": false,
      "virtual_machine": false,
      "sensor_out_of_date": false,
      "sensor_pending_update": false,
      "policy_override": false,
      "quarantined": false,
      "asset_group": []
    }
  },
  "raw": null,
  "inputs": {
    "vmware_cbc_device_id": "210476652"
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-vmware-cbc",
    "package_version": "1.0.0",
    "host": "my.app.host",
    "execution_time_ms": 15881,
    "timestamp": "2024-05-10 13:34:09"
  }
}
